from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cell import Cell
from openapi_server import util

from openapi_server.models.cell import Cell  # noqa: E501

class Cells(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cells=None):  # noqa: E501
        """Cells - a model defined in OpenAPI

        :param cells: The cells of this Cells.  # noqa: E501
        :type cells: List[Cell]
        """
        self.openapi_types = {
            'cells': List[Cell]
        }

        self.attribute_map = {
            'cells': 'cells'
        }

        self._cells = cells

    @classmethod
    def from_dict(cls, dikt) -> 'Cells':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cells of this Cells.  # noqa: E501
        :rtype: Cells
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cells(self) -> List[Cell]:
        """Gets the cells of this Cells.


        :return: The cells of this Cells.
        :rtype: List[Cell]
        """
        return self._cells

    @cells.setter
    def cells(self, cells: List[Cell]):
        """Sets the cells of this Cells.


        :param cells: The cells of this Cells.
        :type cells: List[Cell]
        """

        self._cells = cells
