from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.linear_ring import LinearRing
from openapi_server import util

from openapi_server.models.linear_ring import LinearRing  # noqa: E501

class Cell(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, outer_ring=None, inner_rings=None, area=None):  # noqa: E501
        """Cell - a model defined in OpenAPI

        :param outer_ring: The outer_ring of this Cell.  # noqa: E501
        :type outer_ring: LinearRing
        :param inner_rings: The inner_rings of this Cell.  # noqa: E501
        :type inner_rings: List[LinearRing]
        :param area: The area of this Cell.  # noqa: E501
        :type area: float
        """
        self.openapi_types = {
            'outer_ring': LinearRing,
            'inner_rings': List[LinearRing],
            'area': float
        }

        self.attribute_map = {
            'outer_ring': 'outerRing',
            'inner_rings': 'innerRings',
            'area': 'area'
        }

        self._outer_ring = outer_ring
        self._inner_rings = inner_rings
        self._area = area

    @classmethod
    def from_dict(cls, dikt) -> 'Cell':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cell of this Cell.  # noqa: E501
        :rtype: Cell
        """
        return util.deserialize_model(dikt, cls)

    @property
    def outer_ring(self) -> LinearRing:
        """Gets the outer_ring of this Cell.


        :return: The outer_ring of this Cell.
        :rtype: LinearRing
        """
        return self._outer_ring

    @outer_ring.setter
    def outer_ring(self, outer_ring: LinearRing):
        """Sets the outer_ring of this Cell.


        :param outer_ring: The outer_ring of this Cell.
        :type outer_ring: LinearRing
        """

        self._outer_ring = outer_ring

    @property
    def inner_rings(self) -> List[LinearRing]:
        """Gets the inner_rings of this Cell.


        :return: The inner_rings of this Cell.
        :rtype: List[LinearRing]
        """
        return self._inner_rings

    @inner_rings.setter
    def inner_rings(self, inner_rings: List[LinearRing]):
        """Sets the inner_rings of this Cell.


        :param inner_rings: The inner_rings of this Cell.
        :type inner_rings: List[LinearRing]
        """

        self._inner_rings = inner_rings

    @property
    def area(self) -> float:
        """Gets the area of this Cell.


        :return: The area of this Cell.
        :rtype: float
        """
        return self._area

    @area.setter
    def area(self, area: float):
        """Sets the area of this Cell.


        :param area: The area of this Cell.
        :type area: float
        """

        self._area = area
