from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateRobotRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, robot_width=None, coverage_width=None, min_turning_radius=None):  # noqa: E501
        """CreateRobotRequest - a model defined in OpenAPI

        :param robot_width: The robot_width of this CreateRobotRequest.  # noqa: E501
        :type robot_width: float
        :param coverage_width: The coverage_width of this CreateRobotRequest.  # noqa: E501
        :type coverage_width: float
        :param min_turning_radius: The min_turning_radius of this CreateRobotRequest.  # noqa: E501
        :type min_turning_radius: float
        """
        self.openapi_types = {
            'robot_width': float,
            'coverage_width': float,
            'min_turning_radius': float
        }

        self.attribute_map = {
            'robot_width': 'robotWidth',
            'coverage_width': 'coverageWidth',
            'min_turning_radius': 'minTurningRadius'
        }

        self._robot_width = robot_width
        self._coverage_width = coverage_width
        self._min_turning_radius = min_turning_radius

    @classmethod
    def from_dict(cls, dikt) -> 'CreateRobotRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createRobot_request of this CreateRobotRequest.  # noqa: E501
        :rtype: CreateRobotRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def robot_width(self) -> float:
        """Gets the robot_width of this CreateRobotRequest.

        Robot width in meters  # noqa: E501

        :return: The robot_width of this CreateRobotRequest.
        :rtype: float
        """
        return self._robot_width

    @robot_width.setter
    def robot_width(self, robot_width: float):
        """Sets the robot_width of this CreateRobotRequest.

        Robot width in meters  # noqa: E501

        :param robot_width: The robot_width of this CreateRobotRequest.
        :type robot_width: float
        """
        if robot_width is None:
            raise ValueError("Invalid value for `robot_width`, must not be `None`")  # noqa: E501

        self._robot_width = robot_width

    @property
    def coverage_width(self) -> float:
        """Gets the coverage_width of this CreateRobotRequest.

        Coverage/working width in meters  # noqa: E501

        :return: The coverage_width of this CreateRobotRequest.
        :rtype: float
        """
        return self._coverage_width

    @coverage_width.setter
    def coverage_width(self, coverage_width: float):
        """Sets the coverage_width of this CreateRobotRequest.

        Coverage/working width in meters  # noqa: E501

        :param coverage_width: The coverage_width of this CreateRobotRequest.
        :type coverage_width: float
        """
        if coverage_width is None:
            raise ValueError("Invalid value for `coverage_width`, must not be `None`")  # noqa: E501

        self._coverage_width = coverage_width

    @property
    def min_turning_radius(self) -> float:
        """Gets the min_turning_radius of this CreateRobotRequest.

        Minimum turning radius in meters  # noqa: E501

        :return: The min_turning_radius of this CreateRobotRequest.
        :rtype: float
        """
        return self._min_turning_radius

    @min_turning_radius.setter
    def min_turning_radius(self, min_turning_radius: float):
        """Sets the min_turning_radius of this CreateRobotRequest.

        Minimum turning radius in meters  # noqa: E501

        :param min_turning_radius: The min_turning_radius of this CreateRobotRequest.
        :type min_turning_radius: float
        """

        self._min_turning_radius = min_turning_radius
