from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cells import Cells
from openapi_server import util

from openapi_server.models.cells import Cells  # noqa: E501

class GenerateSwathsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, angle=None, width=None, cells=None):  # noqa: E501
        """GenerateSwathsRequest - a model defined in OpenAPI

        :param angle: The angle of this GenerateSwathsRequest.  # noqa: E501
        :type angle: float
        :param width: The width of this GenerateSwathsRequest.  # noqa: E501
        :type width: float
        :param cells: The cells of this GenerateSwathsRequest.  # noqa: E501
        :type cells: Cells
        """
        self.openapi_types = {
            'angle': float,
            'width': float,
            'cells': Cells
        }

        self.attribute_map = {
            'angle': 'angle',
            'width': 'width',
            'cells': 'cells'
        }

        self._angle = angle
        self._width = width
        self._cells = cells

    @classmethod
    def from_dict(cls, dikt) -> 'GenerateSwathsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The generateSwaths_request of this GenerateSwathsRequest.  # noqa: E501
        :rtype: GenerateSwathsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def angle(self) -> float:
        """Gets the angle of this GenerateSwathsRequest.

        Swath angle in radians  # noqa: E501

        :return: The angle of this GenerateSwathsRequest.
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle: float):
        """Sets the angle of this GenerateSwathsRequest.

        Swath angle in radians  # noqa: E501

        :param angle: The angle of this GenerateSwathsRequest.
        :type angle: float
        """
        if angle is None:
            raise ValueError("Invalid value for `angle`, must not be `None`")  # noqa: E501

        self._angle = angle

    @property
    def width(self) -> float:
        """Gets the width of this GenerateSwathsRequest.

        Coverage width in meters  # noqa: E501

        :return: The width of this GenerateSwathsRequest.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width: float):
        """Sets the width of this GenerateSwathsRequest.

        Coverage width in meters  # noqa: E501

        :param width: The width of this GenerateSwathsRequest.
        :type width: float
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width

    @property
    def cells(self) -> Cells:
        """Gets the cells of this GenerateSwathsRequest.


        :return: The cells of this GenerateSwathsRequest.
        :rtype: Cells
        """
        return self._cells

    @cells.setter
    def cells(self, cells: Cells):
        """Sets the cells of this GenerateSwathsRequest.


        :param cells: The cells of this GenerateSwathsRequest.
        :type cells: Cells
        """
        if cells is None:
            raise ValueError("Invalid value for `cells`, must not be `None`")  # noqa: E501

        self._cells = cells
