from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cells import Cells
from openapi_server import util

from openapi_server.models.cells import Cells  # noqa: E501

class GenerateHeadlandsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cells=None, width=None):  # noqa: E501
        """GenerateHeadlandsRequest - a model defined in OpenAPI

        :param cells: The cells of this GenerateHeadlandsRequest.  # noqa: E501
        :type cells: Cells
        :param width: The width of this GenerateHeadlandsRequest.  # noqa: E501
        :type width: float
        """
        self.openapi_types = {
            'cells': Cells,
            'width': float
        }

        self.attribute_map = {
            'cells': 'cells',
            'width': 'width'
        }

        self._cells = cells
        self._width = width

    @classmethod
    def from_dict(cls, dikt) -> 'GenerateHeadlandsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The generateHeadlands_request of this GenerateHeadlandsRequest.  # noqa: E501
        :rtype: GenerateHeadlandsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cells(self) -> Cells:
        """Gets the cells of this GenerateHeadlandsRequest.


        :return: The cells of this GenerateHeadlandsRequest.
        :rtype: Cells
        """
        return self._cells

    @cells.setter
    def cells(self, cells: Cells):
        """Sets the cells of this GenerateHeadlandsRequest.


        :param cells: The cells of this GenerateHeadlandsRequest.
        :type cells: Cells
        """
        if cells is None:
            raise ValueError("Invalid value for `cells`, must not be `None`")  # noqa: E501

        self._cells = cells

    @property
    def width(self) -> float:
        """Gets the width of this GenerateHeadlandsRequest.

        Headland width (typically 3.0 * robot width)  # noqa: E501

        :return: The width of this GenerateHeadlandsRequest.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width: float):
        """Sets the width of this GenerateHeadlandsRequest.

        Headland width (typically 3.0 * robot width)  # noqa: E501

        :param width: The width of this GenerateHeadlandsRequest.
        :type width: float
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width
