from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.point import Point
from openapi_server import util

from openapi_server.models.point import Point  # noqa: E501

class LinearRing(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, points=None):  # noqa: E501
        """LinearRing - a model defined in OpenAPI

        :param points: The points of this LinearRing.  # noqa: E501
        :type points: List[Point]
        """
        self.openapi_types = {
            'points': List[Point]
        }

        self.attribute_map = {
            'points': 'points'
        }

        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'LinearRing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinearRing of this LinearRing.  # noqa: E501
        :rtype: LinearRing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def points(self) -> List[Point]:
        """Gets the points of this LinearRing.


        :return: The points of this LinearRing.
        :rtype: List[Point]
        """
        return self._points

    @points.setter
    def points(self, points: List[Point]):
        """Sets the points of this LinearRing.


        :param points: The points of this LinearRing.
        :type points: List[Point]
        """

        self._points = points
