from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.cells import Cells
from openapi_server import util

from openapi_server.models.cells import Cells  # noqa: E501

class ModelField(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, crs=None, cells=None, area=None):  # noqa: E501
        """ModelField - a model defined in OpenAPI

        :param id: The id of this ModelField.  # noqa: E501
        :type id: str
        :param crs: The crs of this ModelField.  # noqa: E501
        :type crs: str
        :param cells: The cells of this ModelField.  # noqa: E501
        :type cells: Cells
        :param area: The area of this ModelField.  # noqa: E501
        :type area: float
        """
        self.openapi_types = {
            'id': str,
            'crs': str,
            'cells': Cells,
            'area': float
        }

        self.attribute_map = {
            'id': 'id',
            'crs': 'crs',
            'cells': 'cells',
            'area': 'area'
        }

        self._id = id
        self._crs = crs
        self._cells = cells
        self._area = area

    @classmethod
    def from_dict(cls, dikt) -> 'ModelField':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Field of this ModelField.  # noqa: E501
        :rtype: ModelField
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ModelField.

        Field identifier  # noqa: E501

        :return: The id of this ModelField.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ModelField.

        Field identifier  # noqa: E501

        :param id: The id of this ModelField.
        :type id: str
        """

        self._id = id

    @property
    def crs(self) -> str:
        """Gets the crs of this ModelField.

        Coordinate reference system (e.g., \"EPSG:4258\", \"EPSG:28992\")  # noqa: E501

        :return: The crs of this ModelField.
        :rtype: str
        """
        return self._crs

    @crs.setter
    def crs(self, crs: str):
        """Sets the crs of this ModelField.

        Coordinate reference system (e.g., \"EPSG:4258\", \"EPSG:28992\")  # noqa: E501

        :param crs: The crs of this ModelField.
        :type crs: str
        """

        self._crs = crs

    @property
    def cells(self) -> Cells:
        """Gets the cells of this ModelField.


        :return: The cells of this ModelField.
        :rtype: Cells
        """
        return self._cells

    @cells.setter
    def cells(self, cells: Cells):
        """Sets the cells of this ModelField.


        :param cells: The cells of this ModelField.
        :type cells: Cells
        """

        self._cells = cells

    @property
    def area(self) -> float:
        """Gets the area of this ModelField.

        Field area in square meters  # noqa: E501

        :return: The area of this ModelField.
        :rtype: float
        """
        return self._area

    @area.setter
    def area(self, area: float):
        """Sets the area of this ModelField.

        Field area in square meters  # noqa: E501

        :param area: The area of this ModelField.
        :type area: float
        """

        self._area = area
