from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.point import Point
from openapi_server import util

from openapi_server.models.point import Point  # noqa: E501

class PathState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, point=None, angle=None, velocity=None, length=None, type=None, curvature=None):  # noqa: E501
        """PathState - a model defined in OpenAPI

        :param point: The point of this PathState.  # noqa: E501
        :type point: Point
        :param angle: The angle of this PathState.  # noqa: E501
        :type angle: float
        :param velocity: The velocity of this PathState.  # noqa: E501
        :type velocity: float
        :param length: The length of this PathState.  # noqa: E501
        :type length: float
        :param type: The type of this PathState.  # noqa: E501
        :type type: str
        :param curvature: The curvature of this PathState.  # noqa: E501
        :type curvature: float
        """
        self.openapi_types = {
            'point': Point,
            'angle': float,
            'velocity': float,
            'length': float,
            'type': str,
            'curvature': float
        }

        self.attribute_map = {
            'point': 'point',
            'angle': 'angle',
            'velocity': 'velocity',
            'length': 'length',
            'type': 'type',
            'curvature': 'curvature'
        }

        self._point = point
        self._angle = angle
        self._velocity = velocity
        self._length = length
        self._type = type
        self._curvature = curvature

    @classmethod
    def from_dict(cls, dikt) -> 'PathState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PathState of this PathState.  # noqa: E501
        :rtype: PathState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def point(self) -> Point:
        """Gets the point of this PathState.


        :return: The point of this PathState.
        :rtype: Point
        """
        return self._point

    @point.setter
    def point(self, point: Point):
        """Sets the point of this PathState.


        :param point: The point of this PathState.
        :type point: Point
        """

        self._point = point

    @property
    def angle(self) -> float:
        """Gets the angle of this PathState.

        Heading angle in radians  # noqa: E501

        :return: The angle of this PathState.
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle: float):
        """Sets the angle of this PathState.

        Heading angle in radians  # noqa: E501

        :param angle: The angle of this PathState.
        :type angle: float
        """

        self._angle = angle

    @property
    def velocity(self) -> float:
        """Gets the velocity of this PathState.


        :return: The velocity of this PathState.
        :rtype: float
        """
        return self._velocity

    @velocity.setter
    def velocity(self, velocity: float):
        """Sets the velocity of this PathState.


        :param velocity: The velocity of this PathState.
        :type velocity: float
        """

        self._velocity = velocity

    @property
    def length(self) -> float:
        """Gets the length of this PathState.

        Cumulative length to this point  # noqa: E501

        :return: The length of this PathState.
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length: float):
        """Sets the length of this PathState.

        Cumulative length to this point  # noqa: E501

        :param length: The length of this PathState.
        :type length: float
        """

        self._length = length

    @property
    def type(self) -> str:
        """Gets the type of this PathState.


        :return: The type of this PathState.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this PathState.


        :param type: The type of this PathState.
        :type type: str
        """
        allowed_values = ["DRIVE", "TURN", "SWATH"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def curvature(self) -> float:
        """Gets the curvature of this PathState.


        :return: The curvature of this PathState.
        :rtype: float
        """
        return self._curvature

    @curvature.setter
    def curvature(self, curvature: float):
        """Sets the curvature of this PathState.


        :param curvature: The curvature of this PathState.
        :type curvature: float
        """

        self._curvature = curvature
