from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.path_state import PathState
from openapi_server import util

from openapi_server.models.path_state import PathState  # noqa: E501

class Path(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, states=None, length=None):  # noqa: E501
        """Path - a model defined in OpenAPI

        :param states: The states of this Path.  # noqa: E501
        :type states: List[PathState]
        :param length: The length of this Path.  # noqa: E501
        :type length: float
        """
        self.openapi_types = {
            'states': List[PathState],
            'length': float
        }

        self.attribute_map = {
            'states': 'states',
            'length': 'length'
        }

        self._states = states
        self._length = length

    @classmethod
    def from_dict(cls, dikt) -> 'Path':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Path of this Path.  # noqa: E501
        :rtype: Path
        """
        return util.deserialize_model(dikt, cls)

    @property
    def states(self) -> List[PathState]:
        """Gets the states of this Path.


        :return: The states of this Path.
        :rtype: List[PathState]
        """
        return self._states

    @states.setter
    def states(self, states: List[PathState]):
        """Sets the states of this Path.


        :param states: The states of this Path.
        :type states: List[PathState]
        """

        self._states = states

    @property
    def length(self) -> float:
        """Gets the length of this Path.

        Total path length in meters  # noqa: E501

        :return: The length of this Path.
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length: float):
        """Sets the length of this Path.

        Total path length in meters  # noqa: E501

        :param length: The length of this Path.
        :type length: float
        """

        self._length = length
