from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.robot import Robot
from openapi_server.models.swaths import Swaths
from openapi_server import util

from openapi_server.models.robot import Robot  # noqa: E501
from openapi_server.models.swaths import Swaths  # noqa: E501

class PlanPathRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, robot=None, swaths=None, turning_algorithm=None):  # noqa: E501
        """PlanPathRequest - a model defined in OpenAPI

        :param robot: The robot of this PlanPathRequest.  # noqa: E501
        :type robot: Robot
        :param swaths: The swaths of this PlanPathRequest.  # noqa: E501
        :type swaths: Swaths
        :param turning_algorithm: The turning_algorithm of this PlanPathRequest.  # noqa: E501
        :type turning_algorithm: str
        """
        self.openapi_types = {
            'robot': Robot,
            'swaths': Swaths,
            'turning_algorithm': str
        }

        self.attribute_map = {
            'robot': 'robot',
            'swaths': 'swaths',
            'turning_algorithm': 'turningAlgorithm'
        }

        self._robot = robot
        self._swaths = swaths
        self._turning_algorithm = turning_algorithm

    @classmethod
    def from_dict(cls, dikt) -> 'PlanPathRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The planPath_request of this PlanPathRequest.  # noqa: E501
        :rtype: PlanPathRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def robot(self) -> Robot:
        """Gets the robot of this PlanPathRequest.


        :return: The robot of this PlanPathRequest.
        :rtype: Robot
        """
        return self._robot

    @robot.setter
    def robot(self, robot: Robot):
        """Sets the robot of this PlanPathRequest.


        :param robot: The robot of this PlanPathRequest.
        :type robot: Robot
        """
        if robot is None:
            raise ValueError("Invalid value for `robot`, must not be `None`")  # noqa: E501

        self._robot = robot

    @property
    def swaths(self) -> Swaths:
        """Gets the swaths of this PlanPathRequest.


        :return: The swaths of this PlanPathRequest.
        :rtype: Swaths
        """
        return self._swaths

    @swaths.setter
    def swaths(self, swaths: Swaths):
        """Sets the swaths of this PlanPathRequest.


        :param swaths: The swaths of this PlanPathRequest.
        :type swaths: Swaths
        """
        if swaths is None:
            raise ValueError("Invalid value for `swaths`, must not be `None`")  # noqa: E501

        self._swaths = swaths

    @property
    def turning_algorithm(self) -> str:
        """Gets the turning_algorithm of this PlanPathRequest.

        Path planning algorithm for turns  # noqa: E501

        :return: The turning_algorithm of this PlanPathRequest.
        :rtype: str
        """
        return self._turning_algorithm

    @turning_algorithm.setter
    def turning_algorithm(self, turning_algorithm: str):
        """Sets the turning_algorithm of this PlanPathRequest.

        Path planning algorithm for turns  # noqa: E501

        :param turning_algorithm: The turning_algorithm of this PlanPathRequest.
        :type turning_algorithm: str
        """
        allowed_values = ["DUBINS", "DUBINS_CC", "REEDS_SHEPP", "REEDS_SHEPP_HC"]  # noqa: E501
        if turning_algorithm not in allowed_values:
            raise ValueError(
                "Invalid value for `turning_algorithm` ({0}), must be one of {1}"
                .format(turning_algorithm, allowed_values)
            )

        self._turning_algorithm = turning_algorithm
