from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Robot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, robot_width=None, coverage_width=None, min_turning_radius=None, max_curvature=None, max_diff_curvature=None, cruise_velocity=None):  # noqa: E501
        """Robot - a model defined in OpenAPI

        :param robot_width: The robot_width of this Robot.  # noqa: E501
        :type robot_width: float
        :param coverage_width: The coverage_width of this Robot.  # noqa: E501
        :type coverage_width: float
        :param min_turning_radius: The min_turning_radius of this Robot.  # noqa: E501
        :type min_turning_radius: float
        :param max_curvature: The max_curvature of this Robot.  # noqa: E501
        :type max_curvature: float
        :param max_diff_curvature: The max_diff_curvature of this Robot.  # noqa: E501
        :type max_diff_curvature: float
        :param cruise_velocity: The cruise_velocity of this Robot.  # noqa: E501
        :type cruise_velocity: float
        """
        self.openapi_types = {
            'robot_width': float,
            'coverage_width': float,
            'min_turning_radius': float,
            'max_curvature': float,
            'max_diff_curvature': float,
            'cruise_velocity': float
        }

        self.attribute_map = {
            'robot_width': 'robotWidth',
            'coverage_width': 'coverageWidth',
            'min_turning_radius': 'minTurningRadius',
            'max_curvature': 'maxCurvature',
            'max_diff_curvature': 'maxDiffCurvature',
            'cruise_velocity': 'cruiseVelocity'
        }

        self._robot_width = robot_width
        self._coverage_width = coverage_width
        self._min_turning_radius = min_turning_radius
        self._max_curvature = max_curvature
        self._max_diff_curvature = max_diff_curvature
        self._cruise_velocity = cruise_velocity

    @classmethod
    def from_dict(cls, dikt) -> 'Robot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Robot of this Robot.  # noqa: E501
        :rtype: Robot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def robot_width(self) -> float:
        """Gets the robot_width of this Robot.

        Robot width in meters  # noqa: E501

        :return: The robot_width of this Robot.
        :rtype: float
        """
        return self._robot_width

    @robot_width.setter
    def robot_width(self, robot_width: float):
        """Sets the robot_width of this Robot.

        Robot width in meters  # noqa: E501

        :param robot_width: The robot_width of this Robot.
        :type robot_width: float
        """
        if robot_width is None:
            raise ValueError("Invalid value for `robot_width`, must not be `None`")  # noqa: E501

        self._robot_width = robot_width

    @property
    def coverage_width(self) -> float:
        """Gets the coverage_width of this Robot.

        Working/coverage width in meters  # noqa: E501

        :return: The coverage_width of this Robot.
        :rtype: float
        """
        return self._coverage_width

    @coverage_width.setter
    def coverage_width(self, coverage_width: float):
        """Sets the coverage_width of this Robot.

        Working/coverage width in meters  # noqa: E501

        :param coverage_width: The coverage_width of this Robot.
        :type coverage_width: float
        """
        if coverage_width is None:
            raise ValueError("Invalid value for `coverage_width`, must not be `None`")  # noqa: E501

        self._coverage_width = coverage_width

    @property
    def min_turning_radius(self) -> float:
        """Gets the min_turning_radius of this Robot.

        Minimum turning radius in meters  # noqa: E501

        :return: The min_turning_radius of this Robot.
        :rtype: float
        """
        return self._min_turning_radius

    @min_turning_radius.setter
    def min_turning_radius(self, min_turning_radius: float):
        """Sets the min_turning_radius of this Robot.

        Minimum turning radius in meters  # noqa: E501

        :param min_turning_radius: The min_turning_radius of this Robot.
        :type min_turning_radius: float
        """

        self._min_turning_radius = min_turning_radius

    @property
    def max_curvature(self) -> float:
        """Gets the max_curvature of this Robot.

        Maximum curvature (1/radius)  # noqa: E501

        :return: The max_curvature of this Robot.
        :rtype: float
        """
        return self._max_curvature

    @max_curvature.setter
    def max_curvature(self, max_curvature: float):
        """Sets the max_curvature of this Robot.

        Maximum curvature (1/radius)  # noqa: E501

        :param max_curvature: The max_curvature of this Robot.
        :type max_curvature: float
        """

        self._max_curvature = max_curvature

    @property
    def max_diff_curvature(self) -> float:
        """Gets the max_diff_curvature of this Robot.

        Maximum curvature change rate  # noqa: E501

        :return: The max_diff_curvature of this Robot.
        :rtype: float
        """
        return self._max_diff_curvature

    @max_diff_curvature.setter
    def max_diff_curvature(self, max_diff_curvature: float):
        """Sets the max_diff_curvature of this Robot.

        Maximum curvature change rate  # noqa: E501

        :param max_diff_curvature: The max_diff_curvature of this Robot.
        :type max_diff_curvature: float
        """

        self._max_diff_curvature = max_diff_curvature

    @property
    def cruise_velocity(self) -> float:
        """Gets the cruise_velocity of this Robot.

        Cruise velocity in m/s  # noqa: E501

        :return: The cruise_velocity of this Robot.
        :rtype: float
        """
        return self._cruise_velocity

    @cruise_velocity.setter
    def cruise_velocity(self, cruise_velocity: float):
        """Sets the cruise_velocity of this Robot.

        Cruise velocity in m/s  # noqa: E501

        :param cruise_velocity: The cruise_velocity of this Robot.
        :type cruise_velocity: float
        """

        self._cruise_velocity = cruise_velocity
