from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.visualization_layer import VisualizationLayer
from openapi_server import util

from openapi_server.models.visualization_layer import VisualizationLayer  # noqa: E501

class SaveVisualizationRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, filename=None, layers=None):  # noqa: E501
        """SaveVisualizationRequest - a model defined in OpenAPI

        :param filename: The filename of this SaveVisualizationRequest.  # noqa: E501
        :type filename: str
        :param layers: The layers of this SaveVisualizationRequest.  # noqa: E501
        :type layers: List[VisualizationLayer]
        """
        self.openapi_types = {
            'filename': str,
            'layers': List[VisualizationLayer]
        }

        self.attribute_map = {
            'filename': 'filename',
            'layers': 'layers'
        }

        self._filename = filename
        self._layers = layers

    @classmethod
    def from_dict(cls, dikt) -> 'SaveVisualizationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The saveVisualization_request of this SaveVisualizationRequest.  # noqa: E501
        :rtype: SaveVisualizationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filename(self) -> str:
        """Gets the filename of this SaveVisualizationRequest.

        Output filename  # noqa: E501

        :return: The filename of this SaveVisualizationRequest.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this SaveVisualizationRequest.

        Output filename  # noqa: E501

        :param filename: The filename of this SaveVisualizationRequest.
        :type filename: str
        """
        if filename is None:
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def layers(self) -> List[VisualizationLayer]:
        """Gets the layers of this SaveVisualizationRequest.

        Layers to visualize  # noqa: E501

        :return: The layers of this SaveVisualizationRequest.
        :rtype: List[VisualizationLayer]
        """
        return self._layers

    @layers.setter
    def layers(self, layers: List[VisualizationLayer]):
        """Sets the layers of this SaveVisualizationRequest.

        Layers to visualize  # noqa: E501

        :param layers: The layers of this SaveVisualizationRequest.
        :type layers: List[VisualizationLayer]
        """
        if layers is None:
            raise ValueError("Invalid value for `layers`, must not be `None`")  # noqa: E501

        self._layers = layers
