from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SaveVisualization200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, file_path=None):  # noqa: E501
        """SaveVisualization200Response - a model defined in OpenAPI

        :param success: The success of this SaveVisualization200Response.  # noqa: E501
        :type success: bool
        :param file_path: The file_path of this SaveVisualization200Response.  # noqa: E501
        :type file_path: str
        """
        self.openapi_types = {
            'success': bool,
            'file_path': str
        }

        self.attribute_map = {
            'success': 'success',
            'file_path': 'filePath'
        }

        self._success = success
        self._file_path = file_path

    @classmethod
    def from_dict(cls, dikt) -> 'SaveVisualization200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The saveVisualization_200_response of this SaveVisualization200Response.  # noqa: E501
        :rtype: SaveVisualization200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this SaveVisualization200Response.


        :return: The success of this SaveVisualization200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this SaveVisualization200Response.


        :param success: The success of this SaveVisualization200Response.
        :type success: bool
        """

        self._success = success

    @property
    def file_path(self) -> str:
        """Gets the file_path of this SaveVisualization200Response.


        :return: The file_path of this SaveVisualization200Response.
        :rtype: str
        """
        return self._file_path

    @file_path.setter
    def file_path(self, file_path: str):
        """Sets the file_path of this SaveVisualization200Response.


        :param file_path: The file_path of this SaveVisualization200Response.
        :type file_path: str
        """

        self._file_path = file_path
