from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.swaths import Swaths
from openapi_server import util

from openapi_server.models.swaths import Swaths  # noqa: E501

class SortSwathsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, swaths=None, variant=0):  # noqa: E501
        """SortSwathsRequest - a model defined in OpenAPI

        :param swaths: The swaths of this SortSwathsRequest.  # noqa: E501
        :type swaths: Swaths
        :param variant: The variant of this SortSwathsRequest.  # noqa: E501
        :type variant: int
        """
        self.openapi_types = {
            'swaths': Swaths,
            'variant': int
        }

        self.attribute_map = {
            'swaths': 'swaths',
            'variant': 'variant'
        }

        self._swaths = swaths
        self._variant = variant

    @classmethod
    def from_dict(cls, dikt) -> 'SortSwathsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sortSwaths_request of this SortSwathsRequest.  # noqa: E501
        :rtype: SortSwathsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def swaths(self) -> Swaths:
        """Gets the swaths of this SortSwathsRequest.


        :return: The swaths of this SortSwathsRequest.
        :rtype: Swaths
        """
        return self._swaths

    @swaths.setter
    def swaths(self, swaths: Swaths):
        """Sets the swaths of this SortSwathsRequest.


        :param swaths: The swaths of this SortSwathsRequest.
        :type swaths: Swaths
        """
        if swaths is None:
            raise ValueError("Invalid value for `swaths`, must not be `None`")  # noqa: E501

        self._swaths = swaths

    @property
    def variant(self) -> int:
        """Gets the variant of this SortSwathsRequest.

        Sorting variant (0-3 for different start positions)  # noqa: E501

        :return: The variant of this SortSwathsRequest.
        :rtype: int
        """
        return self._variant

    @variant.setter
    def variant(self, variant: int):
        """Sets the variant of this SortSwathsRequest.

        Sorting variant (0-3 for different start positions)  # noqa: E501

        :param variant: The variant of this SortSwathsRequest.
        :type variant: int
        """
        if variant is not None and variant > 3:  # noqa: E501
            raise ValueError("Invalid value for `variant`, must be a value less than or equal to `3`")  # noqa: E501
        if variant is not None and variant < 0:  # noqa: E501
            raise ValueError("Invalid value for `variant`, must be a value greater than or equal to `0`")  # noqa: E501

        self._variant = variant
