from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.swath import Swath
from openapi_server import util

from openapi_server.models.swath import Swath  # noqa: E501

class Swaths(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, swaths=None):  # noqa: E501
        """Swaths - a model defined in OpenAPI

        :param swaths: The swaths of this Swaths.  # noqa: E501
        :type swaths: List[Swath]
        """
        self.openapi_types = {
            'swaths': List[Swath]
        }

        self.attribute_map = {
            'swaths': 'swaths'
        }

        self._swaths = swaths

    @classmethod
    def from_dict(cls, dikt) -> 'Swaths':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Swaths of this Swaths.  # noqa: E501
        :rtype: Swaths
        """
        return util.deserialize_model(dikt, cls)

    @property
    def swaths(self) -> List[Swath]:
        """Gets the swaths of this Swaths.


        :return: The swaths of this Swaths.
        :rtype: List[Swath]
        """
        return self._swaths

    @swaths.setter
    def swaths(self, swaths: List[Swath]):
        """Sets the swaths of this Swaths.


        :param swaths: The swaths of this Swaths.
        :type swaths: List[Swath]
        """

        self._swaths = swaths
