from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.line_string import LineString
from openapi_server import util

from openapi_server.models.line_string import LineString  # noqa: E501

class Swath(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None, width=None, id=None):  # noqa: E501
        """Swath - a model defined in OpenAPI

        :param path: The path of this Swath.  # noqa: E501
        :type path: LineString
        :param width: The width of this Swath.  # noqa: E501
        :type width: float
        :param id: The id of this Swath.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'path': LineString,
            'width': float,
            'id': int
        }

        self.attribute_map = {
            'path': 'path',
            'width': 'width',
            'id': 'id'
        }

        self._path = path
        self._width = width
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Swath':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Swath of this Swath.  # noqa: E501
        :rtype: Swath
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> LineString:
        """Gets the path of this Swath.


        :return: The path of this Swath.
        :rtype: LineString
        """
        return self._path

    @path.setter
    def path(self, path: LineString):
        """Sets the path of this Swath.


        :param path: The path of this Swath.
        :type path: LineString
        """

        self._path = path

    @property
    def width(self) -> float:
        """Gets the width of this Swath.


        :return: The width of this Swath.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width: float):
        """Sets the width of this Swath.


        :param width: The width of this Swath.
        :type width: float
        """

        self._width = width

    @property
    def id(self) -> int:
        """Gets the id of this Swath.


        :return: The id of this Swath.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Swath.


        :param id: The id of this Swath.
        :type id: int
        """

        self._id = id
