from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.model_field import ModelField
from openapi_server.models.path import Path
from openapi_server import util

from openapi_server.models.model_field import ModelField  # noqa: E501
from openapi_server.models.path import Path  # noqa: E501

class TransformToPrevCRSRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None, _field=None):  # noqa: E501
        """TransformToPrevCRSRequest - a model defined in OpenAPI

        :param path: The path of this TransformToPrevCRSRequest.  # noqa: E501
        :type path: Path
        :param _field: The _field of this TransformToPrevCRSRequest.  # noqa: E501
        :type _field: ModelField
        """
        self.openapi_types = {
            'path': Path,
            '_field': ModelField
        }

        self.attribute_map = {
            'path': 'path',
            '_field': 'field'
        }

        self._path = path
        self.__field = _field

    @classmethod
    def from_dict(cls, dikt) -> 'TransformToPrevCRSRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transformToPrevCRS_request of this TransformToPrevCRSRequest.  # noqa: E501
        :rtype: TransformToPrevCRSRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> Path:
        """Gets the path of this TransformToPrevCRSRequest.


        :return: The path of this TransformToPrevCRSRequest.
        :rtype: Path
        """
        return self._path

    @path.setter
    def path(self, path: Path):
        """Sets the path of this TransformToPrevCRSRequest.


        :param path: The path of this TransformToPrevCRSRequest.
        :type path: Path
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def _field(self) -> ModelField:
        """Gets the _field of this TransformToPrevCRSRequest.


        :return: The _field of this TransformToPrevCRSRequest.
        :rtype: ModelField
        """
        return self.__field

    @_field.setter
    def _field(self, _field: ModelField):
        """Sets the _field of this TransformToPrevCRSRequest.


        :param _field: The _field of this TransformToPrevCRSRequest.
        :type _field: ModelField
        """
        if _field is None:
            raise ValueError("Invalid value for `_field`, must not be `None`")  # noqa: E501

        self.__field = _field
