from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.model_field import ModelField
from openapi_server import util

from openapi_server.models.model_field import ModelField  # noqa: E501

class TransformToUTMRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _field=None, is_etrs89=True):  # noqa: E501
        """TransformToUTMRequest - a model defined in OpenAPI

        :param _field: The _field of this TransformToUTMRequest.  # noqa: E501
        :type _field: ModelField
        :param is_etrs89: The is_etrs89 of this TransformToUTMRequest.  # noqa: E501
        :type is_etrs89: bool
        """
        self.openapi_types = {
            '_field': ModelField,
            'is_etrs89': bool
        }

        self.attribute_map = {
            '_field': 'field',
            'is_etrs89': 'isETRS89'
        }

        self.__field = _field
        self._is_etrs89 = is_etrs89

    @classmethod
    def from_dict(cls, dikt) -> 'TransformToUTMRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transformToUTM_request of this TransformToUTMRequest.  # noqa: E501
        :rtype: TransformToUTMRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _field(self) -> ModelField:
        """Gets the _field of this TransformToUTMRequest.


        :return: The _field of this TransformToUTMRequest.
        :rtype: ModelField
        """
        return self.__field

    @_field.setter
    def _field(self, _field: ModelField):
        """Sets the _field of this TransformToUTMRequest.


        :param _field: The _field of this TransformToUTMRequest.
        :type _field: ModelField
        """
        if _field is None:
            raise ValueError("Invalid value for `_field`, must not be `None`")  # noqa: E501

        self.__field = _field

    @property
    def is_etrs89(self) -> bool:
        """Gets the is_etrs89 of this TransformToUTMRequest.

        Use ETRS89 datum (default true)  # noqa: E501

        :return: The is_etrs89 of this TransformToUTMRequest.
        :rtype: bool
        """
        return self._is_etrs89

    @is_etrs89.setter
    def is_etrs89(self, is_etrs89: bool):
        """Sets the is_etrs89 of this TransformToUTMRequest.

        Use ETRS89 datum (default true)  # noqa: E501

        :param is_etrs89: The is_etrs89 of this TransformToUTMRequest.
        :type is_etrs89: bool
        """

        self._is_etrs89 = is_etrs89
