from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VisualizationLayer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, data=None):  # noqa: E501
        """VisualizationLayer - a model defined in OpenAPI

        :param type: The type of this VisualizationLayer.  # noqa: E501
        :type type: str
        :param data: The data of this VisualizationLayer.  # noqa: E501
        :type data: object
        """
        self.openapi_types = {
            'type': str,
            'data': object
        }

        self.attribute_map = {
            'type': 'type',
            'data': 'data'
        }

        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'VisualizationLayer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisualizationLayer of this VisualizationLayer.  # noqa: E501
        :rtype: VisualizationLayer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this VisualizationLayer.


        :return: The type of this VisualizationLayer.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this VisualizationLayer.


        :param type: The type of this VisualizationLayer.
        :type type: str
        """
        allowed_values = ["FIELD", "CELLS", "PATH", "SWATHS", "ROUTE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def data(self) -> object:
        """Gets the data of this VisualizationLayer.

        Geometry data to visualize  # noqa: E501

        :return: The data of this VisualizationLayer.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this VisualizationLayer.

        Geometry data to visualize  # noqa: E501

        :param data: The data of this VisualizationLayer.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
