/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fields:parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a GeoJSON FeatureCollection into a typed Field
         * @description Accepts an inline GeoJSON FeatureCollection, projects it to a local metric
         *     CRS (UTM), and returns a typed `Field` payload ready to feed to
         *     `/headlands:generate` verbatim.
         */
        post: operations["parseField"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/headlands:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate headland rings for a parsed field
         * @description Generates headland rings around a parsed field's boundary and returns a
         *     `FieldWithHeadlands` payload containing the original field, the headland
         *     ring geometry, and the inner cultivable area. Feed the response verbatim
         *     to `/swaths:generate`. The field ships in the request body — the server
         *     is stateless and does not store fields.
         */
        post: operations["generateHeadlands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swaths:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate coverage swaths inside a field's inner (post-headland) area
         * @description Generates parallel coverage swaths inside the inner cultivable area of a
         *     `FieldWithHeadlands` at the supplied heading. Returns a `Swaths` payload
         *     ready to feed to `/swaths:sort`. The field-with-headlands ships in the
         *     request body — the server is stateless.
         */
        post: operations["generateSwaths"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swaths:sort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order swaths into a traversal sequence
         * @description Orders an unsorted `Swaths` payload into a traversal sequence according to
         *     the selected algorithm (e.g., boustrophedon). Returns the same `Swaths`
         *     shape with `sorted=true`, ready to feed to `/routes:generate`.
         */
        post: operations["sortSwaths"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a route with turn connections between sorted swaths
         * @description Builds a `Route` from sorted swaths by inserting turn connections between
         *     consecutive swath groups. The field and swaths are carried forward in the
         *     response so `/paths:plan` receives everything it needs in one payload.
         */
        post: operations["generateRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paths:plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a smooth drivable path from a route (terminal step)
         * @description Plans a smooth drivable path through a `Route` using the selected turning
         *     algorithm. This is the terminal step of the pipeline; the response's
         *     `journey.next` link is null.
         */
        post: operations["planPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/plan-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the full coverage pipeline in one round-trip (80% case)
         * @description One-shot shortcut that executes the full field->headland->swath->sort->
         *     route->path pipeline server-side. Returns the terminal `Path` plus
         *     every intermediate payload so clients can introspect / debug / reuse
         *     pieces of the run. All business logic is shared with the granular
         *     journey endpoints (SHC-03).
         */
        post: operations["planCoverage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/plan-swaths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cheap prefix of the pipeline — stops after sort-swaths
         * @description Runs the pipeline's cheap prefix (parse -> headland -> swaths ->
         *     sort) in one round-trip and stops there. Clients typically call
         *     this to preview the swath layout on a map, let the user tweak
         *     settings, and only pay for the expensive tail (route + path)
         *     when the user explicitly commits via `/pipeline/resume` with
         *     `start_step=generate-route` and the sorted swaths from this
         *     response. Shares the same per-step helpers as the granular
         *     endpoints (SHC-03).
         */
        post: operations["planSwaths"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume the pipeline from an arbitrary intermediate step
         * @description Accepts any intermediate payload from a prior journey run (a `Field`,
         *     `FieldWithHeadlands`, `Swaths`, sorted `Swaths`, or `Route`) and
         *     executes every subsequent step. Lets clients cherry-pick which
         *     steps to override without re-running the earlier ones. Shares the
         *     same per-step helpers as the granular endpoints (SHC-03).
         */
        post: operations["resumePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error envelope returned on 4xx/5xx responses */
        Error: {
            /**
             * @description Stable machine-readable error code
             * @example INVALID_GEOJSON
             */
            code: string;
            /** @description Human-readable error message */
            message: string;
            /** @description Optional extra context */
            details?: string;
        };
        /**
         * @description Navigation metadata sibling to every response payload. Clients follow
         *     `next.uri` to chain pipeline steps. `back.uri` allows re-running an
         *     earlier step with a modified payload.
         */
        Journey: {
            /**
             * @description Canonical step identifier
             * @enum {string}
             */
            step_name: "fields:parse" | "headlands:generate" | "swaths:generate" | "swaths:sort" | "routes:generate" | "paths:plan";
            /** @description Link to the next step, or null if this is the terminal step */
            next: components["schemas"]["JourneyLink"] | null;
            /** @description Link back to the previous step, or null if this is the first step */
            back: components["schemas"]["JourneyLink"] | null;
        };
        /** @description Hypermedia link pointing at the next or previous journey step */
        JourneyLink: {
            /**
             * @description Absolute URI template for the linked step
             * @example /fields/{id}/headlands:generate
             */
            uri: string;
            /** @enum {string} */
            method: "POST";
            /**
             * @description JSON pointer to the body schema the linked step accepts
             * @example #/components/schemas/GenerateHeadlandsRequest
             */
            body_schema_ref: string;
        };
        /** @description RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted */
        GeoJSONFeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            features: {
                /** @enum {string} */
                type: "Feature";
                properties?: Record<string, never> | null;
                /** @description GeoJSON geometry (Polygon, MultiPolygon, LineString, etc.) */
                geometry: Record<string, never>;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** @description Coordinate reference system descriptor (EPSG-only in v2.0) */
        CRS: {
            /**
             * @description EPSG code (e.g., 4326 for WGS84, 32631 for UTM31N)
             * @example 32631
             */
            epsg: number;
            /**
             * @description Optional UTM zone hint
             * @example 31N
             */
            utm_zone?: string;
        };
        /**
         * @description Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
         *     `crs` (typically a local UTM zone after parsing). Downstream steps
         *     operate in this CRS until `/paths:plan` returns the final path.
         */
        Field: {
            /** @description Opaque client-visible handle (echoed in journey URIs) */
            id: string;
            crs: components["schemas"]["CRS"];
            geometry: components["schemas"]["GeoJSONFeatureCollection"];
            /** @description [x, y] local-metric origin used for projection */
            ref_point?: number[];
        };
        /**
         * @description A `Field` augmented with computed headland rings and the inner cultivable
         *     area. Feed this verbatim to `/fields/{id}/swaths:generate`.
         */
        FieldWithHeadlands: {
            field: components["schemas"]["Field"];
            /** @description Headland ring geometry in field.crs */
            headlands: components["schemas"]["GeoJSONFeatureCollection"];
            /** @description Inner cultivable cells (field minus headlands) in field.crs */
            inner_field: components["schemas"]["GeoJSONFeatureCollection"];
            /** Format: double */
            headland_width_m: number;
        };
        /** @description A single coverage swath line bound to a parent field's CRS */
        Swath: {
            id: number;
            /** @description GeoJSON LineString geometry in the parent field's CRS */
            path: {
                /** @enum {string} */
                type: "LineString";
                coordinates: number[][];
            };
            /** Format: double */
            width_m: number;
            /** @enum {string} */
            type: "MAINLAND" | "HEADLAND";
        };
        /**
         * @description An ordered list of swaths bound to the field they were generated for.
         *     `field` is carried forward so sort/route/path steps do not need to
         *     re-parse it.
         */
        Swaths: {
            field: components["schemas"]["FieldWithHeadlands"];
            items: components["schemas"]["Swath"][];
            /**
             * @description True once /swaths:sort has produced an ordering
             * @default false
             */
            sorted: boolean;
        };
        /** @description Turn connection between two swaths (MultiPoint in field CRS) */
        RouteConnection: {
            from_swath_id: number;
            to_swath_id: number;
            points: number[][];
        };
        /** @description Ordered swath groups + turn connections. Feed to /paths:plan. */
        Route: {
            field: components["schemas"]["FieldWithHeadlands"];
            swaths: components["schemas"]["Swaths"];
            connections: components["schemas"]["RouteConnection"][];
        };
        /** @description Single pose along a planned drivable path */
        PathState: {
            point: number[];
            /** Format: double */
            angle_rad: number;
            /** Format: double */
            length_m: number;
            /** Format: double */
            velocity: number;
            /** @enum {string} */
            direction: "FORWARD" | "BACKWARD";
            /** @enum {string} */
            section_type: "SWATH" | "TURN";
        };
        /**
         * @description Terminal coverage path as a sequence of PathStates in field.crs. The
         *     `journey.next` link on the response is null — this is the end of the
         *     pipeline.
         */
        Path: {
            field: components["schemas"]["FieldWithHeadlands"];
            states: components["schemas"]["PathState"][];
            /** Format: double */
            length_m: number;
            /** Format: double */
            task_time_s: number;
        };
        /** @description Robot specification. Passed on every endpoint that needs it. */
        Robot: {
            name?: string;
            /** Format: double */
            width_m: number;
            /** Format: double */
            cov_width_m: number;
            /** Format: double */
            min_turning_radius_m?: number;
            /** Format: double */
            max_curv?: number;
            /** Format: double */
            max_diff_curv?: number;
            /** Format: double */
            cruise_vel_mps?: number;
            /** Format: double */
            turn_vel_mps?: number;
        };
        /** @description Request body for /fields:parse */
        ParseFieldRequest: {
            /** @description Raw input FeatureCollection (WGS84 expected) */
            geojson: components["schemas"]["GeoJSONFeatureCollection"];
            /**
             * @description Optional target CRS for projection. If omitted, the server picks an
             *     appropriate local UTM zone based on the input centroid.
             */
            target_crs?: components["schemas"]["CRS"];
        };
        /** @description Response body for /fields:parse */
        ParseFieldResponse: {
            field: components["schemas"]["Field"];
            journey: components["schemas"]["Journey"];
        };
        /** @description Request body for /fields/{id}/headlands:generate */
        GenerateHeadlandsRequest: {
            field: components["schemas"]["Field"];
            robot: components["schemas"]["Robot"];
            /**
             * Format: double
             * @description Headland ring width in meters
             */
            width_m: number;
            /**
             * @description Number of headland rings
             * @default 3
             */
            count: number;
        };
        /** @description Response body for /fields/{id}/headlands:generate */
        GenerateHeadlandsResponse: {
            field_with_headlands: components["schemas"]["FieldWithHeadlands"];
            journey: components["schemas"]["Journey"];
        };
        /** @description Request body for /fields/{id}/swaths:generate */
        GenerateSwathsRequest: {
            field_with_headlands: components["schemas"]["FieldWithHeadlands"];
            robot: components["schemas"]["Robot"];
            /**
             * Format: double
             * @description Swath heading in radians (0 = east). When omitted the server
             *     automatically selects the heading that minimises the number of
             *     swaths (brute-force search over [0, π)).
             */
            angle_rad?: number;
            /** Format: double */
            width_m: number;
        };
        /** @description Response body for /fields/{id}/swaths:generate */
        GenerateSwathsResponse: {
            swaths: components["schemas"]["Swaths"];
            journey: components["schemas"]["Journey"];
        };
        /** @description Request body for /swaths:sort */
        SortSwathsRequest: {
            swaths: components["schemas"]["Swaths"];
            /**
             * @default BOUSTROPHEDON
             * @enum {string}
             */
            algorithm: "BOUSTROPHEDON" | "SNAKE" | "SPIRAL";
            /** @default 0 */
            variant: number;
        };
        /** @description Response body for /swaths:sort */
        SortSwathsResponse: {
            /** @description Same Swaths shape, now with sorted=true */
            swaths: components["schemas"]["Swaths"];
            journey: components["schemas"]["Journey"];
        };
        /** @description Request body for /routes:generate */
        GenerateRouteRequest: {
            /** @description Sorted swaths (field is embedded) */
            swaths: components["schemas"]["Swaths"];
        };
        /** @description Response body for /routes:generate */
        GenerateRouteResponse: {
            route: components["schemas"]["Route"];
            journey: components["schemas"]["Journey"];
        };
        /** @description Request body for /paths:plan */
        PlanPathRequest: {
            route: components["schemas"]["Route"];
            robot: components["schemas"]["Robot"];
            /** @enum {string} */
            turning_algorithm: "DUBINS" | "DUBINS_CC" | "REEDS_SHEPP" | "REEDS_SHEPP_HC";
        };
        /** @description Response body for /paths:plan */
        PlanPathResponse: {
            path: components["schemas"]["Path"];
            journey: components["schemas"]["Journey"];
        };
        /**
         * @description Full-pipeline input. The server picks the local UTM zone if
         *     target_crs is omitted. SortAlgorithm / variant / headland_count
         *     default to the same values the granular endpoints use.
         */
        PlanCoverageRequest: {
            geojson: components["schemas"]["GeoJSONFeatureCollection"];
            target_crs?: components["schemas"]["CRS"];
            robot: components["schemas"]["Robot"];
            /** Format: double */
            headland_width_m: number;
            /** @default 3 */
            headland_count: number;
            /**
             * Format: double
             * @description Swath heading in radians (0 = east). When omitted the server
             *     automatically selects the heading that minimises the number of
             *     swaths (brute-force search over [0, π)).
             */
            swath_angle_rad?: number;
            /** Format: double */
            swath_width_m: number;
            /**
             * @default BOUSTROPHEDON
             * @enum {string}
             */
            sort_algorithm: "BOUSTROPHEDON" | "SNAKE" | "SPIRAL";
            /** @default 0 */
            sort_variant: number;
            /**
             * @description WGS84 [lng, lat] of the desired route start point. When set, the server
             *     auto-selects the sort variant whose first swath is nearest to this point.
             *     Takes priority over sort_variant when both are provided.
             */
            sort_start_point?: number[];
            /** @enum {string} */
            turning_algorithm: "DUBINS" | "DUBINS_CC" | "REEDS_SHEPP" | "REEDS_SHEPP_HC";
        };
        /**
         * @description Every intermediate payload produced by a full pipeline run. On a
         *     RunAll response, every field is populated. On a RunFrom response,
         *     only the fields from the start step onward are populated -- the
         *     earlier fields are whatever the caller supplied (echoed back).
         */
        FieldIntermediates: {
            field?: components["schemas"]["Field"];
            field_with_headlands?: components["schemas"]["FieldWithHeadlands"];
            swaths?: components["schemas"]["Swaths"];
            sorted_swaths?: components["schemas"]["Swaths"];
            route?: components["schemas"]["Route"];
        };
        /**
         * @description Full-pipeline output. `path` is the terminal planned path; every
         *     intermediate payload is returned under `intermediates` for
         *     debuggability and partial reuse. `journey.next` is null (the
         *     full pipeline is terminal -- the only follow-up is to re-run with
         *     different params).
         */
        PlanCoverageResponse: {
            path: components["schemas"]["Path"];
            intermediates: components["schemas"]["FieldIntermediates"];
            journey: components["schemas"]["Journey"];
        };
        /**
         * @description Output of the cheap `/pipeline/plan-swaths` prefix. Contains the
         *     projected field with headlands and the sorted swaths but NOT the
         *     generated route or terminal path. Feed `sorted_swaths` into
         *     `/pipeline/resume` with `start_step=generate-route` to complete
         *     the run when the user commits. `journey.next` points at the
         *     resume endpoint so the client UX can chain the two calls.
         */
        PlanSwathsResponse: {
            field_with_headlands: components["schemas"]["FieldWithHeadlands"];
            sorted_swaths: components["schemas"]["Swaths"];
            journey: components["schemas"]["Journey"];
        };
        /**
         * @description Resume-from-step input. Exactly one of {field, field_with_headlands,
         *     swaths, sorted_swaths, route} must be populated, and it must match
         *     start_step (e.g. start_step="sort-swaths" pairs with swaths; see
         *     the per-step table in the description of `start_step`).
         */
        ResumePipelineRequest: {
            /**
             * @description Step to start execution from. "parse-field" is intentionally
             *     not a valid start step -- call /pipeline/plan-coverage instead.
             *     Pairings:
             *       generate-headland -> field
             *       generate-swaths   -> field_with_headlands
             *       sort-swaths       -> swaths
             *       generate-route    -> sorted_swaths
             *       plan-path         -> route
             * @enum {string}
             */
            start_step: "generate-headland" | "generate-swaths" | "sort-swaths" | "generate-route" | "plan-path";
            field?: components["schemas"]["Field"];
            field_with_headlands?: components["schemas"]["FieldWithHeadlands"];
            swaths?: components["schemas"]["Swaths"];
            sorted_swaths?: components["schemas"]["Swaths"];
            route?: components["schemas"]["Route"];
            robot: components["schemas"]["Robot"];
            /** Format: double */
            headland_width_m?: number;
            /** @default 3 */
            headland_count: number;
            /**
             * Format: double
             * @description Swath heading in radians (0 = east). When omitted the server
             *     automatically selects the heading that minimises the number of
             *     swaths (brute-force search over [0, π)).
             */
            swath_angle_rad?: number;
            /** Format: double */
            swath_width_m?: number;
            /**
             * @default BOUSTROPHEDON
             * @enum {string}
             */
            sort_algorithm: "BOUSTROPHEDON" | "SNAKE" | "SPIRAL";
            /** @default 0 */
            sort_variant: number;
            /** @enum {string} */
            turning_algorithm: "DUBINS" | "DUBINS_CC" | "REEDS_SHEPP" | "REEDS_SHEPP_HC";
        };
    };
    responses: {
        /** @description Malformed request or validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parseField: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseFieldRequest"];
            };
        };
        responses: {
            /** @description Field parsed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseFieldResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    generateHeadlands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateHeadlandsRequest"];
            };
        };
        responses: {
            /** @description Headlands generated; field is now ready for swath generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateHeadlandsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    generateSwaths: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSwathsRequest"];
            };
        };
        responses: {
            /** @description Swaths generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateSwathsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    sortSwaths: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SortSwathsRequest"];
            };
        };
        responses: {
            /** @description Swaths sorted into traversal order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SortSwathsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    generateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRouteRequest"];
            };
        };
        responses: {
            /** @description Route built */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateRouteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    planPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanPathRequest"];
            };
        };
        responses: {
            /** @description Drivable path planned (terminal step; journey.next is null) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPathResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    planCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCoverageRequest"];
            };
        };
        responses: {
            /** @description Full pipeline executed; path + all intermediates returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCoverageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["BadRequest"];
        };
    };
    planSwaths: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCoverageRequest"];
            };
        };
        responses: {
            /** @description Swaths planned and sorted; route+path NOT generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSwathsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["BadRequest"];
        };
    };
    resumePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumePipelineRequest"];
            };
        };
        responses: {
            /** @description Pipeline resumed; result includes the supplied intermediates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCoverageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["BadRequest"];
        };
    };
}
