// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for GeoJSONFeatureCollectionFeaturesType.
const (
	Feature GeoJSONFeatureCollectionFeaturesType = "Feature"
)

// Defines values for GeoJSONFeatureCollectionType.
const (
	FeatureCollection GeoJSONFeatureCollectionType = "FeatureCollection"
)

// Defines values for JourneyStepName.
const (
	FieldsParse       JourneyStepName = "fields:parse"
	HeadlandsGenerate JourneyStepName = "headlands:generate"
	PathsPlan         JourneyStepName = "paths:plan"
	RoutesGenerate    JourneyStepName = "routes:generate"
	SwathsGenerate    JourneyStepName = "swaths:generate"
	SwathsSort        JourneyStepName = "swaths:sort"
)

// Defines values for JourneyLinkMethod.
const (
	POST JourneyLinkMethod = "POST"
)

// Defines values for PathStateDirection.
const (
	BACKWARD PathStateDirection = "BACKWARD"
	FORWARD  PathStateDirection = "FORWARD"
)

// Defines values for PathStateSectionType.
const (
	SWATH PathStateSectionType = "SWATH"
	TURN  PathStateSectionType = "TURN"
)

// Defines values for PlanCoverageRequestSortAlgorithm.
const (
	PlanCoverageRequestSortAlgorithmBOUSTROPHEDON PlanCoverageRequestSortAlgorithm = "BOUSTROPHEDON"
	PlanCoverageRequestSortAlgorithmSNAKE         PlanCoverageRequestSortAlgorithm = "SNAKE"
	PlanCoverageRequestSortAlgorithmSPIRAL        PlanCoverageRequestSortAlgorithm = "SPIRAL"
)

// Defines values for PlanCoverageRequestTurningAlgorithm.
const (
	PlanCoverageRequestTurningAlgorithmDUBINS       PlanCoverageRequestTurningAlgorithm = "DUBINS"
	PlanCoverageRequestTurningAlgorithmDUBINSCC     PlanCoverageRequestTurningAlgorithm = "DUBINS_CC"
	PlanCoverageRequestTurningAlgorithmREEDSSHEPP   PlanCoverageRequestTurningAlgorithm = "REEDS_SHEPP"
	PlanCoverageRequestTurningAlgorithmREEDSSHEPPHC PlanCoverageRequestTurningAlgorithm = "REEDS_SHEPP_HC"
)

// Defines values for PlanPathRequestTurningAlgorithm.
const (
	PlanPathRequestTurningAlgorithmDUBINS       PlanPathRequestTurningAlgorithm = "DUBINS"
	PlanPathRequestTurningAlgorithmDUBINSCC     PlanPathRequestTurningAlgorithm = "DUBINS_CC"
	PlanPathRequestTurningAlgorithmREEDSSHEPP   PlanPathRequestTurningAlgorithm = "REEDS_SHEPP"
	PlanPathRequestTurningAlgorithmREEDSSHEPPHC PlanPathRequestTurningAlgorithm = "REEDS_SHEPP_HC"
)

// Defines values for ResumePipelineRequestSortAlgorithm.
const (
	ResumePipelineRequestSortAlgorithmBOUSTROPHEDON ResumePipelineRequestSortAlgorithm = "BOUSTROPHEDON"
	ResumePipelineRequestSortAlgorithmSNAKE         ResumePipelineRequestSortAlgorithm = "SNAKE"
	ResumePipelineRequestSortAlgorithmSPIRAL        ResumePipelineRequestSortAlgorithm = "SPIRAL"
)

// Defines values for ResumePipelineRequestStartStep.
const (
	GenerateHeadland ResumePipelineRequestStartStep = "generate-headland"
	GenerateRoute    ResumePipelineRequestStartStep = "generate-route"
	GenerateSwaths   ResumePipelineRequestStartStep = "generate-swaths"
	PlanPath         ResumePipelineRequestStartStep = "plan-path"
	SortSwaths       ResumePipelineRequestStartStep = "sort-swaths"
)

// Defines values for ResumePipelineRequestTurningAlgorithm.
const (
	DUBINS       ResumePipelineRequestTurningAlgorithm = "DUBINS"
	DUBINSCC     ResumePipelineRequestTurningAlgorithm = "DUBINS_CC"
	REEDSSHEPP   ResumePipelineRequestTurningAlgorithm = "REEDS_SHEPP"
	REEDSSHEPPHC ResumePipelineRequestTurningAlgorithm = "REEDS_SHEPP_HC"
)

// Defines values for SortSwathsRequestAlgorithm.
const (
	BOUSTROPHEDON SortSwathsRequestAlgorithm = "BOUSTROPHEDON"
	SNAKE         SortSwathsRequestAlgorithm = "SNAKE"
	SPIRAL        SortSwathsRequestAlgorithm = "SPIRAL"
)

// Defines values for SwathPathType.
const (
	LineString SwathPathType = "LineString"
)

// Defines values for SwathType.
const (
	HEADLAND SwathType = "HEADLAND"
	MAINLAND SwathType = "MAINLAND"
)

// CRS Coordinate reference system descriptor (EPSG-only in v2.0)
type CRS struct {
	// Epsg EPSG code (e.g., 4326 for WGS84, 32631 for UTM31N)
	Epsg int `json:"epsg"`

	// UtmZone Optional UTM zone hint
	UtmZone *string `json:"utm_zone,omitempty"`
}

// Error Error envelope returned on 4xx/5xx responses
type Error struct {
	// Code Stable machine-readable error code
	Code string `json:"code"`

	// Details Optional extra context
	Details *string `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
// `crs` (typically a local UTM zone after parsing). Downstream steps
// operate in this CRS until `/paths:plan` returns the final path.
type Field struct {
	// Crs Coordinate reference system descriptor (EPSG-only in v2.0)
	Crs CRS `json:"crs"`

	// Geometry RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
	Geometry GeoJSONFeatureCollection `json:"geometry"`

	// Id Opaque client-visible handle (echoed in journey URIs)
	Id string `json:"id"`

	// RefPoint [x, y] local-metric origin used for projection
	RefPoint *[]float64 `json:"ref_point,omitempty"`
}

// FieldIntermediates Every intermediate payload produced by a full pipeline run. On a
// RunAll response, every field is populated. On a RunFrom response,
// only the fields from the start step onward are populated -- the
// earlier fields are whatever the caller supplied (echoed back).
type FieldIntermediates struct {
	// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
	// `crs` (typically a local UTM zone after parsing). Downstream steps
	// operate in this CRS until `/paths:plan` returns the final path.
	Field *Field `json:"field,omitempty"`

	// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	FieldWithHeadlands *FieldWithHeadlands `json:"field_with_headlands,omitempty"`

	// Route Ordered swath groups + turn connections. Feed to /paths:plan.
	Route *Route `json:"route,omitempty"`

	// SortedSwaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	SortedSwaths *Swaths `json:"sorted_swaths,omitempty"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths *Swaths `json:"swaths,omitempty"`
}

// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
type FieldWithHeadlands struct {
	// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
	// `crs` (typically a local UTM zone after parsing). Downstream steps
	// operate in this CRS until `/paths:plan` returns the final path.
	Field          Field   `json:"field"`
	HeadlandWidthM float64 `json:"headland_width_m"`

	// Headlands RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
	Headlands GeoJSONFeatureCollection `json:"headlands"`

	// InnerField RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
	InnerField GeoJSONFeatureCollection `json:"inner_field"`
}

// GenerateHeadlandsRequest Request body for /fields/{id}/headlands:generate
type GenerateHeadlandsRequest struct {
	// Count Number of headland rings
	Count *int `json:"count,omitempty"`

	// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
	// `crs` (typically a local UTM zone after parsing). Downstream steps
	// operate in this CRS until `/paths:plan` returns the final path.
	Field Field `json:"field"`

	// Robot Robot specification. Passed on every endpoint that needs it.
	Robot Robot `json:"robot"`

	// WidthM Headland ring width in meters
	WidthM float64 `json:"width_m"`
}

// GenerateHeadlandsResponse Response body for /fields/{id}/headlands:generate
type GenerateHeadlandsResponse struct {
	// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	FieldWithHeadlands FieldWithHeadlands `json:"field_with_headlands"`

	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`
}

// GenerateRouteRequest Request body for /routes:generate
type GenerateRouteRequest struct {
	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths Swaths `json:"swaths"`
}

// GenerateRouteResponse Response body for /routes:generate
type GenerateRouteResponse struct {
	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// Route Ordered swath groups + turn connections. Feed to /paths:plan.
	Route Route `json:"route"`
}

// GenerateSwathsRequest Request body for /fields/{id}/swaths:generate
type GenerateSwathsRequest struct {
	// AngleRad Swath heading in radians (0 = east). When omitted the server
	// automatically selects the heading that minimises the number of
	// swaths (brute-force search over [0, π)).
	AngleRad *float64 `json:"angle_rad,omitempty"`

	// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	FieldWithHeadlands FieldWithHeadlands `json:"field_with_headlands"`

	// Robot Robot specification. Passed on every endpoint that needs it.
	Robot  Robot   `json:"robot"`
	WidthM float64 `json:"width_m"`
}

// GenerateSwathsResponse Response body for /fields/{id}/swaths:generate
type GenerateSwathsResponse struct {
	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths Swaths `json:"swaths"`
}

// GeoJSONFeatureCollection RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
type GeoJSONFeatureCollection struct {
	Features []struct {
		// Geometry GeoJSON geometry (Polygon, MultiPolygon, LineString, etc.)
		Geometry   map[string]interface{}               `json:"geometry"`
		Properties *map[string]interface{}              `json:"properties"`
		Type       GeoJSONFeatureCollectionFeaturesType `json:"type"`
	} `json:"features"`
	Type                 GeoJSONFeatureCollectionType `json:"type"`
	AdditionalProperties map[string]interface{}       `json:"-"`
}

// GeoJSONFeatureCollectionFeaturesType defines model for GeoJSONFeatureCollection.Features.Type.
type GeoJSONFeatureCollectionFeaturesType string

// GeoJSONFeatureCollectionType defines model for GeoJSONFeatureCollection.Type.
type GeoJSONFeatureCollectionType string

// Journey Navigation metadata sibling to every response payload. Clients follow
// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
// earlier step with a modified payload.
type Journey struct {
	// Back Link back to the previous step, or null if this is the first step
	Back *JourneyLink `json:"back"`

	// Next Link to the next step, or null if this is the terminal step
	Next *JourneyLink `json:"next"`

	// StepName Canonical step identifier
	StepName JourneyStepName `json:"step_name"`
}

// JourneyStepName Canonical step identifier
type JourneyStepName string

// JourneyLink Hypermedia link pointing at the next or previous journey step
type JourneyLink struct {
	// BodySchemaRef JSON pointer to the body schema the linked step accepts
	BodySchemaRef string            `json:"body_schema_ref"`
	Method        JourneyLinkMethod `json:"method"`

	// Uri Absolute URI template for the linked step
	Uri string `json:"uri"`
}

// JourneyLinkMethod defines model for JourneyLink.Method.
type JourneyLinkMethod string

// ParseFieldRequest Request body for /fields:parse
type ParseFieldRequest struct {
	// Geojson RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
	Geojson GeoJSONFeatureCollection `json:"geojson"`

	// TargetCrs Coordinate reference system descriptor (EPSG-only in v2.0)
	TargetCrs *CRS `json:"target_crs,omitempty"`
}

// ParseFieldResponse Response body for /fields:parse
type ParseFieldResponse struct {
	// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
	// `crs` (typically a local UTM zone after parsing). Downstream steps
	// operate in this CRS until `/paths:plan` returns the final path.
	Field Field `json:"field"`

	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`
}

// Path Terminal coverage path as a sequence of PathStates in field.crs. The
// `journey.next` link on the response is null — this is the end of the
// pipeline.
type Path struct {
	// Field A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	Field     FieldWithHeadlands `json:"field"`
	LengthM   float64            `json:"length_m"`
	States    []PathState        `json:"states"`
	TaskTimeS float64            `json:"task_time_s"`
}

// PathState Single pose along a planned drivable path
type PathState struct {
	AngleRad    float64              `json:"angle_rad"`
	Direction   PathStateDirection   `json:"direction"`
	LengthM     float64              `json:"length_m"`
	Point       []float64            `json:"point"`
	SectionType PathStateSectionType `json:"section_type"`
	Velocity    float64              `json:"velocity"`
}

// PathStateDirection defines model for PathState.Direction.
type PathStateDirection string

// PathStateSectionType defines model for PathState.SectionType.
type PathStateSectionType string

// PlanCoverageRequest Full-pipeline input. The server picks the local UTM zone if
// target_crs is omitted. SortAlgorithm / variant / headland_count
// default to the same values the granular endpoints use.
type PlanCoverageRequest struct {
	// Geojson RFC 7946 GeoJSON FeatureCollection in WGS84 unless otherwise noted
	Geojson        GeoJSONFeatureCollection `json:"geojson"`
	HeadlandCount  *int                     `json:"headland_count,omitempty"`
	HeadlandWidthM float64                  `json:"headland_width_m"`

	// Robot Robot specification. Passed on every endpoint that needs it.
	Robot         Robot                             `json:"robot"`
	SortAlgorithm *PlanCoverageRequestSortAlgorithm `json:"sort_algorithm,omitempty"`

	// SortStartPoint WGS84 [lng, lat] of the desired route start point. When set, the server
	// auto-selects the sort variant whose first swath is nearest to this point.
	// Takes priority over sort_variant when both are provided.
	SortStartPoint *[]float64 `json:"sort_start_point,omitempty"`
	SortVariant    *int       `json:"sort_variant,omitempty"`

	// SwathAngleRad Swath heading in radians (0 = east). When omitted the server
	// automatically selects the heading that minimises the number of
	// swaths (brute-force search over [0, π)).
	SwathAngleRad *float64 `json:"swath_angle_rad,omitempty"`
	SwathWidthM   float64  `json:"swath_width_m"`

	// TargetCrs Coordinate reference system descriptor (EPSG-only in v2.0)
	TargetCrs        *CRS                                `json:"target_crs,omitempty"`
	TurningAlgorithm PlanCoverageRequestTurningAlgorithm `json:"turning_algorithm"`
}

// PlanCoverageRequestSortAlgorithm defines model for PlanCoverageRequest.SortAlgorithm.
type PlanCoverageRequestSortAlgorithm string

// PlanCoverageRequestTurningAlgorithm defines model for PlanCoverageRequest.TurningAlgorithm.
type PlanCoverageRequestTurningAlgorithm string

// PlanCoverageResponse Full-pipeline output. `path` is the terminal planned path; every
// intermediate payload is returned under `intermediates` for
// debuggability and partial reuse. `journey.next` is null (the
// full pipeline is terminal -- the only follow-up is to re-run with
// different params).
type PlanCoverageResponse struct {
	// Intermediates Every intermediate payload produced by a full pipeline run. On a
	// RunAll response, every field is populated. On a RunFrom response,
	// only the fields from the start step onward are populated -- the
	// earlier fields are whatever the caller supplied (echoed back).
	Intermediates FieldIntermediates `json:"intermediates"`

	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// Path Terminal coverage path as a sequence of PathStates in field.crs. The
	// `journey.next` link on the response is null — this is the end of the
	// pipeline.
	Path Path `json:"path"`
}

// PlanPathRequest Request body for /paths:plan
type PlanPathRequest struct {
	// Robot Robot specification. Passed on every endpoint that needs it.
	Robot Robot `json:"robot"`

	// Route Ordered swath groups + turn connections. Feed to /paths:plan.
	Route            Route                           `json:"route"`
	TurningAlgorithm PlanPathRequestTurningAlgorithm `json:"turning_algorithm"`
}

// PlanPathRequestTurningAlgorithm defines model for PlanPathRequest.TurningAlgorithm.
type PlanPathRequestTurningAlgorithm string

// PlanPathResponse Response body for /paths:plan
type PlanPathResponse struct {
	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// Path Terminal coverage path as a sequence of PathStates in field.crs. The
	// `journey.next` link on the response is null — this is the end of the
	// pipeline.
	Path Path `json:"path"`
}

// PlanSwathsResponse Output of the cheap `/pipeline/plan-swaths` prefix. Contains the
// projected field with headlands and the sorted swaths but NOT the
// generated route or terminal path. Feed `sorted_swaths` into
// `/pipeline/resume` with `start_step=generate-route` to complete
// the run when the user commits. `journey.next` points at the
// resume endpoint so the client UX can chain the two calls.
type PlanSwathsResponse struct {
	// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	FieldWithHeadlands FieldWithHeadlands `json:"field_with_headlands"`

	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// SortedSwaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	SortedSwaths Swaths `json:"sorted_swaths"`
}

// ResumePipelineRequest Resume-from-step input. Exactly one of {field, field_with_headlands,
// swaths, sorted_swaths, route} must be populated, and it must match
// start_step (e.g. start_step="sort-swaths" pairs with swaths; see
// the per-step table in the description of `start_step`).
type ResumePipelineRequest struct {
	// Field Parsed field. `geometry` is a GeoJSON FeatureCollection expressed in
	// `crs` (typically a local UTM zone after parsing). Downstream steps
	// operate in this CRS until `/paths:plan` returns the final path.
	Field *Field `json:"field,omitempty"`

	// FieldWithHeadlands A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	FieldWithHeadlands *FieldWithHeadlands `json:"field_with_headlands,omitempty"`
	HeadlandCount      *int                `json:"headland_count,omitempty"`
	HeadlandWidthM     *float64            `json:"headland_width_m,omitempty"`

	// Robot Robot specification. Passed on every endpoint that needs it.
	Robot Robot `json:"robot"`

	// Route Ordered swath groups + turn connections. Feed to /paths:plan.
	Route         *Route                              `json:"route,omitempty"`
	SortAlgorithm *ResumePipelineRequestSortAlgorithm `json:"sort_algorithm,omitempty"`
	SortVariant   *int                                `json:"sort_variant,omitempty"`

	// SortedSwaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	SortedSwaths *Swaths `json:"sorted_swaths,omitempty"`

	// StartStep Step to start execution from. "parse-field" is intentionally
	// not a valid start step -- call /pipeline/plan-coverage instead.
	// Pairings:
	//   generate-headland -> field
	//   generate-swaths   -> field_with_headlands
	//   sort-swaths       -> swaths
	//   generate-route    -> sorted_swaths
	//   plan-path         -> route
	StartStep ResumePipelineRequestStartStep `json:"start_step"`

	// SwathAngleRad Swath heading in radians (0 = east). When omitted the server
	// automatically selects the heading that minimises the number of
	// swaths (brute-force search over [0, π)).
	SwathAngleRad *float64 `json:"swath_angle_rad,omitempty"`
	SwathWidthM   *float64 `json:"swath_width_m,omitempty"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths           *Swaths                               `json:"swaths,omitempty"`
	TurningAlgorithm ResumePipelineRequestTurningAlgorithm `json:"turning_algorithm"`
}

// ResumePipelineRequestSortAlgorithm defines model for ResumePipelineRequest.SortAlgorithm.
type ResumePipelineRequestSortAlgorithm string

// ResumePipelineRequestStartStep Step to start execution from. "parse-field" is intentionally
// not a valid start step -- call /pipeline/plan-coverage instead.
// Pairings:
//
//	generate-headland -> field
//	generate-swaths   -> field_with_headlands
//	sort-swaths       -> swaths
//	generate-route    -> sorted_swaths
//	plan-path         -> route
type ResumePipelineRequestStartStep string

// ResumePipelineRequestTurningAlgorithm defines model for ResumePipelineRequest.TurningAlgorithm.
type ResumePipelineRequestTurningAlgorithm string

// Robot Robot specification. Passed on every endpoint that needs it.
type Robot struct {
	CovWidthM         float64  `json:"cov_width_m"`
	CruiseVelMps      *float64 `json:"cruise_vel_mps,omitempty"`
	MaxCurv           *float64 `json:"max_curv,omitempty"`
	MaxDiffCurv       *float64 `json:"max_diff_curv,omitempty"`
	MinTurningRadiusM *float64 `json:"min_turning_radius_m,omitempty"`
	Name              *string  `json:"name,omitempty"`
	TurnVelMps        *float64 `json:"turn_vel_mps,omitempty"`
	WidthM            float64  `json:"width_m"`
}

// Route Ordered swath groups + turn connections. Feed to /paths:plan.
type Route struct {
	Connections []RouteConnection `json:"connections"`

	// Field A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	Field FieldWithHeadlands `json:"field"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths Swaths `json:"swaths"`
}

// RouteConnection Turn connection between two swaths (MultiPoint in field CRS)
type RouteConnection struct {
	FromSwathId int         `json:"from_swath_id"`
	Points      [][]float64 `json:"points"`
	ToSwathId   int         `json:"to_swath_id"`
}

// SortSwathsRequest Request body for /swaths:sort
type SortSwathsRequest struct {
	Algorithm *SortSwathsRequestAlgorithm `json:"algorithm,omitempty"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths  Swaths `json:"swaths"`
	Variant *int   `json:"variant,omitempty"`
}

// SortSwathsRequestAlgorithm defines model for SortSwathsRequest.Algorithm.
type SortSwathsRequestAlgorithm string

// SortSwathsResponse Response body for /swaths:sort
type SortSwathsResponse struct {
	// Journey Navigation metadata sibling to every response payload. Clients follow
	// `next.uri` to chain pipeline steps. `back.uri` allows re-running an
	// earlier step with a modified payload.
	Journey Journey `json:"journey"`

	// Swaths An ordered list of swaths bound to the field they were generated for.
	// `field` is carried forward so sort/route/path steps do not need to
	// re-parse it.
	Swaths Swaths `json:"swaths"`
}

// Swath A single coverage swath line bound to a parent field's CRS
type Swath struct {
	Id int `json:"id"`

	// Path GeoJSON LineString geometry in the parent field's CRS
	Path struct {
		Coordinates [][]float64   `json:"coordinates"`
		Type        SwathPathType `json:"type"`
	} `json:"path"`
	Type   SwathType `json:"type"`
	WidthM float64   `json:"width_m"`
}

// SwathPathType defines model for Swath.Path.Type.
type SwathPathType string

// SwathType defines model for Swath.Type.
type SwathType string

// Swaths An ordered list of swaths bound to the field they were generated for.
// `field` is carried forward so sort/route/path steps do not need to
// re-parse it.
type Swaths struct {
	// Field A `Field` augmented with computed headland rings and the inner cultivable
	// area. Feed this verbatim to `/fields/{id}/swaths:generate`.
	Field FieldWithHeadlands `json:"field"`
	Items []Swath            `json:"items"`

	// Sorted True once /swaths:sort has produced an ordering
	Sorted *bool `json:"sorted,omitempty"`
}

// BadRequest Error envelope returned on 4xx/5xx responses
type BadRequest = Error

// ParseFieldJSONRequestBody defines body for ParseField for application/json ContentType.
type ParseFieldJSONRequestBody = ParseFieldRequest

// GenerateHeadlandsJSONRequestBody defines body for GenerateHeadlands for application/json ContentType.
type GenerateHeadlandsJSONRequestBody = GenerateHeadlandsRequest

// PlanPathJSONRequestBody defines body for PlanPath for application/json ContentType.
type PlanPathJSONRequestBody = PlanPathRequest

// PlanCoverageJSONRequestBody defines body for PlanCoverage for application/json ContentType.
type PlanCoverageJSONRequestBody = PlanCoverageRequest

// PlanSwathsJSONRequestBody defines body for PlanSwaths for application/json ContentType.
type PlanSwathsJSONRequestBody = PlanCoverageRequest

// ResumePipelineJSONRequestBody defines body for ResumePipeline for application/json ContentType.
type ResumePipelineJSONRequestBody = ResumePipelineRequest

// GenerateRouteJSONRequestBody defines body for GenerateRoute for application/json ContentType.
type GenerateRouteJSONRequestBody = GenerateRouteRequest

// GenerateSwathsJSONRequestBody defines body for GenerateSwaths for application/json ContentType.
type GenerateSwathsJSONRequestBody = GenerateSwathsRequest

// SortSwathsJSONRequestBody defines body for SortSwaths for application/json ContentType.
type SortSwathsJSONRequestBody = SortSwathsRequest

// Getter for additional properties for GeoJSONFeatureCollection. Returns the specified
// element and whether it was found
func (a GeoJSONFeatureCollection) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GeoJSONFeatureCollection
func (a *GeoJSONFeatureCollection) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GeoJSONFeatureCollection to handle AdditionalProperties
func (a *GeoJSONFeatureCollection) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GeoJSONFeatureCollection to handle AdditionalProperties
func (a GeoJSONFeatureCollection) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["features"], err = json.Marshal(a.Features)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'features': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Parse a GeoJSON FeatureCollection into a typed Field
	// (POST /fields:parse)
	ParseField(w http.ResponseWriter, r *http.Request)
	// Generate headland rings for a parsed field
	// (POST /headlands:generate)
	GenerateHeadlands(w http.ResponseWriter, r *http.Request)
	// Plan a smooth drivable path from a route (terminal step)
	// (POST /paths:plan)
	PlanPath(w http.ResponseWriter, r *http.Request)
	// Run the full coverage pipeline in one round-trip (80% case)
	// (POST /pipeline/plan-coverage)
	PlanCoverage(w http.ResponseWriter, r *http.Request)
	// Cheap prefix of the pipeline — stops after sort-swaths
	// (POST /pipeline/plan-swaths)
	PlanSwaths(w http.ResponseWriter, r *http.Request)
	// Resume the pipeline from an arbitrary intermediate step
	// (POST /pipeline/resume)
	ResumePipeline(w http.ResponseWriter, r *http.Request)
	// Build a route with turn connections between sorted swaths
	// (POST /routes:generate)
	GenerateRoute(w http.ResponseWriter, r *http.Request)
	// Generate coverage swaths inside a field's inner (post-headland) area
	// (POST /swaths:generate)
	GenerateSwaths(w http.ResponseWriter, r *http.Request)
	// Order swaths into a traversal sequence
	// (POST /swaths:sort)
	SortSwaths(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Parse a GeoJSON FeatureCollection into a typed Field
// (POST /fields:parse)
func (_ Unimplemented) ParseField(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate headland rings for a parsed field
// (POST /headlands:generate)
func (_ Unimplemented) GenerateHeadlands(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Plan a smooth drivable path from a route (terminal step)
// (POST /paths:plan)
func (_ Unimplemented) PlanPath(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Run the full coverage pipeline in one round-trip (80% case)
// (POST /pipeline/plan-coverage)
func (_ Unimplemented) PlanCoverage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cheap prefix of the pipeline — stops after sort-swaths
// (POST /pipeline/plan-swaths)
func (_ Unimplemented) PlanSwaths(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resume the pipeline from an arbitrary intermediate step
// (POST /pipeline/resume)
func (_ Unimplemented) ResumePipeline(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build a route with turn connections between sorted swaths
// (POST /routes:generate)
func (_ Unimplemented) GenerateRoute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate coverage swaths inside a field's inner (post-headland) area
// (POST /swaths:generate)
func (_ Unimplemented) GenerateSwaths(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Order swaths into a traversal sequence
// (POST /swaths:sort)
func (_ Unimplemented) SortSwaths(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ParseField operation middleware
func (siw *ServerInterfaceWrapper) ParseField(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseField(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GenerateHeadlands operation middleware
func (siw *ServerInterfaceWrapper) GenerateHeadlands(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateHeadlands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PlanPath operation middleware
func (siw *ServerInterfaceWrapper) PlanPath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanPath(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PlanCoverage operation middleware
func (siw *ServerInterfaceWrapper) PlanCoverage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanCoverage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PlanSwaths operation middleware
func (siw *ServerInterfaceWrapper) PlanSwaths(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanSwaths(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResumePipeline operation middleware
func (siw *ServerInterfaceWrapper) ResumePipeline(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumePipeline(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GenerateRoute operation middleware
func (siw *ServerInterfaceWrapper) GenerateRoute(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GenerateSwaths operation middleware
func (siw *ServerInterfaceWrapper) GenerateSwaths(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateSwaths(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SortSwaths operation middleware
func (siw *ServerInterfaceWrapper) SortSwaths(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SortSwaths(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/fields:parse", wrapper.ParseField)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/headlands:generate", wrapper.GenerateHeadlands)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/paths:plan", wrapper.PlanPath)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pipeline/plan-coverage", wrapper.PlanCoverage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pipeline/plan-swaths", wrapper.PlanSwaths)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pipeline/resume", wrapper.ResumePipeline)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/routes:generate", wrapper.GenerateRoute)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/swaths:generate", wrapper.GenerateSwaths)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/swaths:sort", wrapper.SortSwaths)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9+3IbudHvq3TNyamVaocUV/ZeIlf+kGV77WTXUkn22VPlUZHQDEhiPQQmAEYSj0tV",
	"eYi813mHPMlX3QDmxiFF2pI3le/LH1lSxKXR+PUVDfhTlKpFoSSX1kRHnyJ+yxZFzunzGdOGvxI8z875",
	"30tu7Ev3I/5mysWC6WV0FP0qpFiwHH7m6q8Xp29hih2iOLpmeUlNZ1z9bpTEj1PObKlx9A/09wW3OAYS",
	"oXQmJLP024cPT4c/fncYf384fPL0MqZvT/u+Hfqvh71fLy8v48guCx4dRWcqX86UjO7iqNCq4NoKnEqW",
	"eV61eeWoi+4uu386UXnOUytwgLu7uMUZUyhpeC9rqFnmOAJCwvt3vz757m2TN45ZyADt2F+YWXT05PCH",
	"J9/FUWkX4/+nJNKB3e7iFsu25uUoHl3GH7578uPwsPHp8PBw+P1l/GHU+DR6HI7Fkciio2iaZ+PR6Lso",
	"jjSfjgslpI2OPvzw3Y+j0Sj+/sc//3k0Gl3exdHvqtSS01KuWPoxTCn5raW/qWw5NumcL9hY82l0FP2v",
	"gxrDB+4Xc/Azl1wzy19zluVMZsZjOIqjBbdzhRSdnV68i+Ko1CI6ig5oL8yBJ/NgHjoezfxQuBJjeTGW",
	"bIFLdR2OCtxlxMUdrszBgTbzOQuC47ZFWi7pIyuKXKQMuXMQRMPRjZ/+tGFVL7VW2mEw4ybVoiAWH0W/",
	"snyq9IJnoN2UoDRcs1xkNA1w3zH2ExGBJ+cXRE6WCWzE8rPGRk9Zbnh3mpMKW6D5lGsuUw5maSxfQGip",
	"NOy9PLv4eaBkvkTYXx8OR/tRG0YB6p86E2BHSFXGYY8PZ8MYnj45/AGmSsNvP1/89DQGkg36g5MmHJgH",
	"4fOC46EopOUzrnHbalHqTnhauKXjcIBNYI7AbAwaOZn1gxqrhZxFbrP/XgrNs+jog1tNLQXq6neeWpzZ",
	"7dhuXKY+wOU1z1WBnLYoERkoCU9vbw++v72FGmhdviLzVpd5YdlVzmHB0rmQfKA5y+gPhAtieGvJb97+",
	"n+Nf3rwY//zyFJX66vKRZMtEbjZwlN9azYBwf2v7hlhwY9ish9rX5YLJLpGh9X1b4RcTmvdtyqugdnfY",
	"lKYyH8IkaNwJCAOssn4r6g/4baG5wa5CJnKSajOBPbssRMryfAkMcpU24cemlmtApSLkbH8IL9SNNFZz",
	"tgBUPiaRSChKoJBg58LAyfkFlNKKHCYHBbNzc1TkTE48bgzYOYepwB3BX4eJXMWMsz6bNA/qio4F+tNG",
	"9Uv8WGsNVkHD/l5ySHPBpR1cCyNw4+dMZjmqgnSuiIHgjQO8P39j9vsw1bAt3Tk+3MawvHT8HuAqRApK",
	"i5mQUNLWKg2FVr97SuNIWL4gxqBqZTY6ijJVXuUNCMpyceU0zILdvnHND+NoIWT9xTdlWrPlClgFukrI",
	"/gZr1yL2jbQcdbxwtn03nXLNNWrjegQo2DJXLMM1Z2XKM7hCOE7LPIdCFDwXkoMu5RBOJbBEnpfyOM8r",
	"zRMDpyG9d2OgUEWZM8sz1wHOS/lKq0XdIZFkERwc0XTCFH/H78YybQnfoOQN0xkwzesRYTDAZonkTOeC",
	"69AfG93MmUVKaByUKa7BlGhheVYhBx2J/T7kVw7YJjA7dXEXu9bjG2Hn48o92Krzb8LOK0+EYKpKy+/r",
	"ek6N0GYrbXk2Njco3ff1unCtsNtO7e/Wwa5N/G6wO4YJjTEBVs4WXOJmIv8ACSnxW2AkoAQbwE+4k0JK",
	"riEtcyuu0QgkkmnOhvCK88ypvWuur5gVC7AKJsF7+ySyuwO37spvm3z5xgcixzcis/PxwoVKaV4acc0p",
	"AioX0ZHVJY97lMUiNBj1KI6tgbRRpSK3xlutaf0wHdUUArmawPY8PVzp01xrHfHdgOR7Abr/pKlbO97j",
	"rK/6RWUwClNW5jY6etKd4y1tCqhpB5TNLex1L3cDk1ZXyt4v+9joLo4aiOs4SU0agZqhhVxwy8mePAg+",
	"12DCLaEmbsuNd4Zg55133T5/6x9ObTdi002d/+qb9bKvS0g96iYuki14KNEh67OBYTsbjuYifectFvNQ",
	"cLhvObvu2m7mubN813W7TXUcfAyF2DGBKyxhcpbzsWY9rjgRRRoQ9YqQoFkmmDSwN4K/AGfG7g/htzmX",
	"oBbCWu7steH6mutEstKqBbM+ujEcrYsLQcKIds4skMoRhrufZFC8iXSEw96VLi0fTJVOcWym0zko9PI+",
	"jGL4///Y987cFo75Q/psn6m3H00Tr6qSXRRzQN9jaOX78Le7SD6ETrpPKtd4Rms547axw5hXJ/Djn5/+",
	"sCElIKTLZkEpc24MKDvn+kYYDlJZnq3aryrV+6mOSdtNmnF5m55ARmgBez6zG8Ov6F1X334Rkl9QHB0D",
	"t+mwEV7XPGrPKss8R+c8cGKlufvDp4hLBPWHKmF8eV8Sh369JyZuB9ZrJ2ts5LbTVgzvm/avNXR3kJe3",
	"7FrMXC52wS3LmGVgxFVOGlH5WDqEyiE0H8IJJUQMTFWeq5tETiS/tcNSiwn2SudMyDpYp/zQECYY7bo2",
	"DHsZ0HygSylxLibrKJribYrGGCxUJqYYMoepe2Iml47/FLE8P53SucMWsvuLkB/pgKDND/wzheW4DrQB",
	"hebXQpWGqIpBaUB0gZi6aE+EPJY2LlEQxR343dVnBA9GoKcNx91Ml+V6QSm2daQ1Dg66EnrCpJJoMN2G",
	"iIxLi3uh0Yn3WG6dNTRisqaGXdW5/i9GaRt5p6atk6ts4f2iUS/A8zl2eNggIsTZ3cTk9bLwCSrIcQMo",
	"lUe4tfVOUJ7OoyUkBD3fO4DtnhV1WU+akebgOmw2GTTXib4jHTxze8PSlBfWtHLlux4/9aTB3XlUrbno",
	"YOqypykdVXUXcXxlVF5aDu/P34DliyJnlpNJ7pDfIvv+IGozHpCUivZ4hdV9sFg5UH4gl7cSixWbGE7X",
	"PjevYpmecTveNj/eYVEg4D5ePKwDtoYbu+UoHiLQvcfdOmN2vuOa3wUtm2IswGacTjSAGWBgEBwy5aCm",
	"gENfWGa5QV/LHdmk2gzh3ZwncuKpGqIymTg9oyQJS2WAhXFq/l//+GdLz3OZ4QSUjA5298vSiythRs7l",
	"LEQOO+YSjQ0nA5WbuGn+ik293hQzH8dWLPjY7EzJGjR48hpLbE+zDiWOxt2gciEwwoVCGQ4sV2hBAA2d",
	"5Blk2uWUCT2bQ+MtAsxM6DpOqHzP0/Pfjs9fRHH0/Pjkb/SxT59/wV5Xh1yPcUoVR8atadx1qi9+O373",
	"Ooqjd+/P3/Yu6ZrnKhV2uRVFHaC4NcWNLWhhpRq6yfQOqb0Yypk88Rrj8yzPqzLPB5WfLWRRWlImPu0B",
	"hUg/OgXROc0V00TWRgS1iE+aDOFCaXucz5QWdr6AA7hmWjBp4aDKPo8pZ51In7EODophCw5UQuSmnGkm",
	"y5xpVE7EQQOl6dVKD2AR27R18+mb0+SPeIqyW24GHeIxC7xvLSJ6fvr+4t356dnrly+o8CEAv/v3i7fH",
	"f3uJ/z17c378S68o0DR0tLnuSNqlAT7kGHPnzF562wIZNygTQC67Px2lIXzmzXAbr6TdBs1sG85dQepm",
	"jmrQx06U3kP7xplGb4pQRee3OH4i37GP3EChBXJn6bJutJJ6NC7hSqHh1Ri3qWuRcR8wPpIyakzf2q0R",
	"jeJg8aQXIg340crH/30yn269Dy9rOzrFcWRLLYWctSUuyNWL98/fvL2IYv9hfHISxdH5y5cvLsYXr1+e",
	"nbW/jV+f3B+qBjVXp0NXNE+XO31E3m9KPstxb9sSVVoyJhP0RSYr6YTgsuCvz1yWKJG9VRzC1IVipcy4",
	"hkmznZlgjIC25KqczdiVyFG4mcShtRUsB83RakDHOw6O8B65vO3iECQ2EOoqNIAqPFyyalAW1EL59BNl",
	"mhKZiSkVDlqcmC1Mb1mG6Fa63OtGt2tjPiOCcdmQbVzmVbfFuZFtou8JfnImcayHCoQbmZwuL3czjbsV",
	"pnxtyQ6Ha0Gutxdax+yHirQ3sPvr4+4+nH3ROc8p6afgl6RzzgqYHAQVcIAsGDjLNYFC86m4HcKJkpYJ",
	"V3mYSF9SVxXCU8K5SjhVBT+uxgm8FbwqLbw9fedGCDmp4A8p3VCQzM59VdCkVSY1ASGtSmSDWM1NueAT",
	"R8HEOWbG8uIvYYIBje9S62pR5NzyRFJeANUXGn78Uhqu8feFsGZFX3oH3KUrE+mmrDxzMM6Fd3WO8P7/",
	"QsqkT+OT3r9RVMNm1uYU/pAyhs+sQNvuyLI99GY4nxM7z/yGfq7yxDEGU60WA5dwd+Hcy1uW2nwJGLap",
	"KXwicmPoozoO3loMLepjB9A7WJSonRsVjDHhXFj3y4LZdJ7IGoGu2h0akEyIL160kggKJrRxyHV/ewaG",
	"e3QWXLuVuCJvj6XGqnE9DbxP/q1KIf8jIsrd6zm/Vvz55WHTZxafVnDru42AYFU+sOW3PC0JpiiTQ0gi",
	"ymAPCGJJhE6koLszJN/5MpFSWWDuekuzdHgwIOUJHfNUJYuFNJbT0eYZE1TZd5RIgEr7V1V/g6QcjZ74",
	"MuVWE2+eoN2kIwfYoyG94P4XeniRbo7qzFqzTZPn2JQWQslu6AxHfUmcA1JW1kMH6a0FeLVbf2uTgroh",
	"TNiPrP8JpR9EyewqVF/b324I8a5O93nQn7uYZuwDpuCpmPoLckM4Y3R7RklfJFH5UoQByXlmQNhhT8Hv",
	"9SPsWKpLYfj4mufjRWEecOAFux2npb7ePnk2xlB6pz5CjsPmoTyW5kFZE6obVrQFzvkIHHvkCrs6NdRE",
	"Uj/Uy53Pp051xnWId2CmVVkY+BaQVZAqKV3G3YQLD6oZc/Zhveqx9ekfUX1Sdew7A/yCU8wvjxSq+hXa",
	"gXp9a3egsZYdj5XbTIcrbm84Bns3KsSje75WDvVOOFKGk/OL1Xut6MM4wz12F902e1cuXmxt2uPk0Df+",
	"aNXWJHe3qrXc9kjV6vq27EJp+7D1z+1qp86h7uM72zua8i/0y7cvum8y+qHyX5tY/e9Y2kt9d766ZlwN",
	"QRU/OF1Nqe8rVUpSywwKRtlsUgnf0G3c1XT2NorAU9hfvVsX59aFvD7O32L+1pMQn6tpNuqPe0pxa/K3",
	"rsFt0ny5RWnxr8dv3v5y/PZFFEevXx6/oI99cvrIXoNTey4x2zhcWleacFFBfxdkSlDefciFoeRsSJsG",
	"WFaXbPHTEm645lCnUadKDxM5mbqbmcJAyrQW7ge6fWsUhaDuZg15Hq64GDIFGHxL55QkUvMBBevogT9s",
	"GdQqSO9VDn1IdJF0S8v2+wC65KBkylvKDebM1Pejmec7Iqma6UqpnLP11ycd+at7f0fXNqeqpyjVKbKB",
	"O69vl7rReSBqgeOzN0N42QqIvjF1/RqpamGAJdKUBdeGVzl8KqFt9WkY0n/9458+OW3ghuUfnYYJB35X",
	"y0S6wz0koZX5dvXmN8LOVWmBZaywLn5LZCLPqtNOZB8lXZq1ilUuY7UMtZM1Wft33CwctpUV6WleO9FI",
	"189BlfryvxuhuUs3EbVB+e6FOx37K1c3mKxYmUgEC8s1Z9kS6lOPhiiiufAPD5ycX8CekHAzF+kcUmY4",
	"TKpCxUkiWXaNYhSSG/W7KExmYMorV+5ovVgay7w9YLbxhsE+cb9RpySoqeVI+xAmn0R2N/HAYpq5q6NU",
	"1eG3dpDzmfBnxe4xBoMy74+Zr5bVxWu3kROirnHnHpvU5x3PGkkeyBQ38Pb0XSJzpQhnCygLX3DJ3TME",
	"4e64kxnCc37DliaYviZ0nfrJRcq9h+Nf6Xl+8WLwZHCSs5KKYkudR0fR3NrCHB0cqIJLo0qd8qHSswPf",
	"2xy0OqFWEZaKpokec0gVAODlFEWRitO0cfJ7OBwNR9gLR2eFiI6iJ8PR8EkouEfi2rW6R5+iQpme+qBj",
	"V2+OMOtgcqU4Kw77bkBYBzVXi+YAl0hC3Pt3v+67s4jwOggDVExZxetQT+BgbBVMg66f9JSJT6pr+I7/",
	"7m0SoeSbLLyZ8ircGXab9Vxlyy3eQ2o+RLZwT4ytswGh6cHaB8vqd4/uP2ftlqjftRW7v87ReujpcDT6",
	"CitqPzT2eUvy/n/PA1LUgJ6d4XS+89StqW/gau0HjReuiJ72y2cbn8URkiDqsBcgYtnMoO2sXHkcte9y",
	"wlqBCfcuzMq7EppcI+aXWLnL5DExvWzLRCInq15JLRupO+B2iWjuH5FhOfgjw5Coxl6JbDnt8doHLqD1",
	"vkWjFD0IWCLpoYuVxy2oDtUZGDMXRa9yrNRqyLA3DQGRROoYXTtjlQ4PtPTJ9MrNlp1FezvYrr1B82AC",
	"+dl0rJeiqlHtbD+rX8iR6sarVQyifebPtfMJuC+TukBqF/s4Wxv4a2WtUdiyVsbOckZ2wyyUsvN2NT3Y",
	"uVblbA4MJueumKI0QU7cQQ7i2yWhE1mlZRDFa27TBb81eKHPWuLxjem/0OHr1nqtki8HeiTgdku7vjJe",
	"V4qdemD6orVlocZwr8X2Z9DkauDn/gPYhpzJdeihB6GYL/Np07O/HrO9p73r8Xsq+cDMUdXNlbZp6U+S",
	"3DG097fJ/SRR8ZFDECn/lYQ3fFba+o+JJNL9N8fd6nYuqd6BERkfwnnjbbZqmZMzqgEt8tIkkq9/sMuo",
	"KkZLyTO0WpkCPeQDoPpOOHDVnIksBE+5CSJEr3kd5zlcoVCi6s/VTKQUFsyZDm8zNS8VJDLcsKxvF+xd",
	"vD4ZjJ7srxOuUCD7iALWvc7xBwjZShlwn1fVqpf1CMueObB/CyzPWztcl/B+lpjF0fdfJJnnpazBX+cd",
	"6msvVBtFjtTAalHA3k+j/02x67bCWWd6+0XzvPQyEbp9Y3zNoasthL3+hEEnHQCVOKJs7vdQTlG0VQXN",
	"pnl90b5+mRH/P5F0NcIqd+GY3zg75vLAbKlKCwqV2YIVMeTc1vWB9oazj4k03Fq0wc7vo+rogi2ry7n8",
	"FgNQcc3BMpHDnlN83xI+9hPZLjnktwhXYZE2V30I14LBmgLHRG6qcOyvuvTv8QkK8h1chnCBmsHUN4+q",
	"arM5zwvKF5iOxtheU1yE5P1/sJ7onL30aAnXorLDhE3al2fOEn5L6uLt6bvaq/xD9MNJUxI7XhlFGE6i",
	"3Aum7fqie5SDA+42eZA1JtE7DnRrqXoTQJcS9ljIbMT9QV0ME8f/SSjmbPxB6eDG7gMFc5WT4MxzJxE3",
	"hF84GuVgnOdc6+WgEOlHl+dLpEvXWUV1SFpkvEqZNt7oIM3g3+hQkpumDCZyKyHc0lq362kfSQ77i3b/",
	"TS12lap2kEQR5KbMLQiZ5mUWFGF4YFR0r518faPtKsxbsuikQQLTV8Jq1vUjfT1Xv0x2XwlZK5PPS0Fv",
	"sFaBHs3aKePHmQ3X9IRHt7Yl1FkkMsU1pqVFQ9gsiGnmNkgrulGZ5isnVi7pUdstdJK7zyGnXFwH0bVz",
	"KkysCsich9B6/KY/73EerqA8Ys6j9djfH5TvaL/R1yMp1ACuSpHbLw8KCUxV5OeikDVwaUNsLY67r+Fs",
	"kTIsmGZ5zvPOiT+iA6O29Wk7NIbrcob+4ZpKY/gK1joEZJW9CfBDFLeT73XeDxffzPkNkFeD+jpNMwWI",
	"46zNAbbPgjYA/lF9tP6XEP8gyG/tqX2ZG9afs1uDOVZlqh3y9hDE1X7vE/zukwEq01mfDtEZORASStlx",
	"gOrLpT5br9k114bl9WsrLE2pTmNGR0StLF+V3Av/lsOVKo3VqpjzTMn9dhKEvJowbyLNnBU8XNQiov6C",
	"KJjE0CMaHZM16UNzXQX1SEherWf7yijuqfNaj2C/0bSv9a7S8fyXY5oQVeN4DXT6UUtPj6B+cv+wTedN",
	"NjrQzPi112Gt89yjgwM68JwrY49+Gv00cv8sjZtic41F+wW9KJQyV3TdXd79VwAAAP//RXXCkylpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
