// Copyright (C) 2026 Wageningen University — BSD-3-Clause
//
// Internal gRPC contract between the Go API server and the f2c C++ shim.
// This file is the single source of truth for what f2c operations the Go API
// can invoke. The C++ server (phase 10) and Go client (phase 11) are both
// generated from this file.
//
// IMPORTANT: This contract is DISJOINT from api-go/openapi.yaml on purpose.
// The Go handler layer explicitly converts between OpenAPI (inline GeoJSON)
// and these proto messages (WKT bytes). See docs/contracts.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: f2c.proto

package f2cclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwathType int32

const (
	SwathType_SWATH_TYPE_UNSPECIFIED SwathType = 0
	SwathType_SWATH_TYPE_MAINLAND    SwathType = 1
	SwathType_SWATH_TYPE_HEADLAND    SwathType = 2
)

// Enum value maps for SwathType.
var (
	SwathType_name = map[int32]string{
		0: "SWATH_TYPE_UNSPECIFIED",
		1: "SWATH_TYPE_MAINLAND",
		2: "SWATH_TYPE_HEADLAND",
	}
	SwathType_value = map[string]int32{
		"SWATH_TYPE_UNSPECIFIED": 0,
		"SWATH_TYPE_MAINLAND":    1,
		"SWATH_TYPE_HEADLAND":    2,
	}
)

func (x SwathType) Enum() *SwathType {
	p := new(SwathType)
	*p = x
	return p
}

func (x SwathType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwathType) Descriptor() protoreflect.EnumDescriptor {
	return file_f2c_proto_enumTypes[0].Descriptor()
}

func (SwathType) Type() protoreflect.EnumType {
	return &file_f2c_proto_enumTypes[0]
}

func (x SwathType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwathType.Descriptor instead.
func (SwathType) EnumDescriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{0}
}

type PathDirection int32

const (
	PathDirection_PATH_DIRECTION_UNSPECIFIED PathDirection = 0
	PathDirection_PATH_DIRECTION_FORWARD     PathDirection = 1
	PathDirection_PATH_DIRECTION_BACKWARD    PathDirection = 2
)

// Enum value maps for PathDirection.
var (
	PathDirection_name = map[int32]string{
		0: "PATH_DIRECTION_UNSPECIFIED",
		1: "PATH_DIRECTION_FORWARD",
		2: "PATH_DIRECTION_BACKWARD",
	}
	PathDirection_value = map[string]int32{
		"PATH_DIRECTION_UNSPECIFIED": 0,
		"PATH_DIRECTION_FORWARD":     1,
		"PATH_DIRECTION_BACKWARD":    2,
	}
)

func (x PathDirection) Enum() *PathDirection {
	p := new(PathDirection)
	*p = x
	return p
}

func (x PathDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_f2c_proto_enumTypes[1].Descriptor()
}

func (PathDirection) Type() protoreflect.EnumType {
	return &file_f2c_proto_enumTypes[1]
}

func (x PathDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathDirection.Descriptor instead.
func (PathDirection) EnumDescriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{1}
}

type PathSectionType int32

const (
	PathSectionType_PATH_SECTION_TYPE_UNSPECIFIED PathSectionType = 0
	PathSectionType_PATH_SECTION_TYPE_SWATH       PathSectionType = 1
	PathSectionType_PATH_SECTION_TYPE_TURN        PathSectionType = 2
)

// Enum value maps for PathSectionType.
var (
	PathSectionType_name = map[int32]string{
		0: "PATH_SECTION_TYPE_UNSPECIFIED",
		1: "PATH_SECTION_TYPE_SWATH",
		2: "PATH_SECTION_TYPE_TURN",
	}
	PathSectionType_value = map[string]int32{
		"PATH_SECTION_TYPE_UNSPECIFIED": 0,
		"PATH_SECTION_TYPE_SWATH":       1,
		"PATH_SECTION_TYPE_TURN":        2,
	}
)

func (x PathSectionType) Enum() *PathSectionType {
	p := new(PathSectionType)
	*p = x
	return p
}

func (x PathSectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathSectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_f2c_proto_enumTypes[2].Descriptor()
}

func (PathSectionType) Type() protoreflect.EnumType {
	return &file_f2c_proto_enumTypes[2]
}

func (x PathSectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathSectionType.Descriptor instead.
func (PathSectionType) EnumDescriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{2}
}

type SortAlgorithm int32

const (
	SortAlgorithm_SORT_ALGORITHM_UNSPECIFIED   SortAlgorithm = 0
	SortAlgorithm_SORT_ALGORITHM_BOUSTROPHEDON SortAlgorithm = 1
	SortAlgorithm_SORT_ALGORITHM_SNAKE         SortAlgorithm = 2
	SortAlgorithm_SORT_ALGORITHM_SPIRAL        SortAlgorithm = 3
)

// Enum value maps for SortAlgorithm.
var (
	SortAlgorithm_name = map[int32]string{
		0: "SORT_ALGORITHM_UNSPECIFIED",
		1: "SORT_ALGORITHM_BOUSTROPHEDON",
		2: "SORT_ALGORITHM_SNAKE",
		3: "SORT_ALGORITHM_SPIRAL",
	}
	SortAlgorithm_value = map[string]int32{
		"SORT_ALGORITHM_UNSPECIFIED":   0,
		"SORT_ALGORITHM_BOUSTROPHEDON": 1,
		"SORT_ALGORITHM_SNAKE":         2,
		"SORT_ALGORITHM_SPIRAL":        3,
	}
)

func (x SortAlgorithm) Enum() *SortAlgorithm {
	p := new(SortAlgorithm)
	*p = x
	return p
}

func (x SortAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_f2c_proto_enumTypes[3].Descriptor()
}

func (SortAlgorithm) Type() protoreflect.EnumType {
	return &file_f2c_proto_enumTypes[3]
}

func (x SortAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortAlgorithm.Descriptor instead.
func (SortAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{3}
}

type TurningAlgorithm int32

const (
	TurningAlgorithm_TURNING_ALGORITHM_UNSPECIFIED    TurningAlgorithm = 0
	TurningAlgorithm_TURNING_ALGORITHM_DUBINS         TurningAlgorithm = 1
	TurningAlgorithm_TURNING_ALGORITHM_DUBINS_CC      TurningAlgorithm = 2
	TurningAlgorithm_TURNING_ALGORITHM_REEDS_SHEPP    TurningAlgorithm = 3
	TurningAlgorithm_TURNING_ALGORITHM_REEDS_SHEPP_HC TurningAlgorithm = 4
)

// Enum value maps for TurningAlgorithm.
var (
	TurningAlgorithm_name = map[int32]string{
		0: "TURNING_ALGORITHM_UNSPECIFIED",
		1: "TURNING_ALGORITHM_DUBINS",
		2: "TURNING_ALGORITHM_DUBINS_CC",
		3: "TURNING_ALGORITHM_REEDS_SHEPP",
		4: "TURNING_ALGORITHM_REEDS_SHEPP_HC",
	}
	TurningAlgorithm_value = map[string]int32{
		"TURNING_ALGORITHM_UNSPECIFIED":    0,
		"TURNING_ALGORITHM_DUBINS":         1,
		"TURNING_ALGORITHM_DUBINS_CC":      2,
		"TURNING_ALGORITHM_REEDS_SHEPP":    3,
		"TURNING_ALGORITHM_REEDS_SHEPP_HC": 4,
	}
)

func (x TurningAlgorithm) Enum() *TurningAlgorithm {
	p := new(TurningAlgorithm)
	*p = x
	return p
}

func (x TurningAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TurningAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_f2c_proto_enumTypes[4].Descriptor()
}

func (TurningAlgorithm) Type() protoreflect.EnumType {
	return &file_f2c_proto_enumTypes[4]
}

func (x TurningAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TurningAlgorithm.Descriptor instead.
func (TurningAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{4}
}

// Coordinate reference system descriptor. EPSG-only in v2.0.
type CRS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPSG code. 0 means "unknown/unprojected".
	Epsg int32 `protobuf:"varint,1,opt,name=epsg,proto3" json:"epsg,omitempty"`
	// Optional UTM zone hint (e.g., "31N"). Empty if not UTM.
	UtmZone string `protobuf:"bytes,2,opt,name=utm_zone,json=utmZone,proto3" json:"utm_zone,omitempty"`
	// Full CRS string as f2c stores it (WKT/PROJ string, for round-trip
	// fidelity with the C++ side).
	Raw           string `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRS) Reset() {
	*x = CRS{}
	mi := &file_f2c_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRS) ProtoMessage() {}

func (x *CRS) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRS.ProtoReflect.Descriptor instead.
func (*CRS) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{0}
}

func (x *CRS) GetEpsg() int32 {
	if x != nil {
		return x.Epsg
	}
	return 0
}

func (x *CRS) GetUtmZone() string {
	if x != nil {
		return x.UtmZone
	}
	return ""
}

func (x *CRS) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

// A 2D point in the active CRS.
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_f2c_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// A parsed field. `geometry_wkt` is the field cells serialized as WKT in
// the CRS given by `crs`.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque client handle (echoed in OpenAPI journey URIs; the server is
	// stateless and does not look this up).
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Crs *CRS   `protobuf:"bytes,2,opt,name=crs,proto3" json:"crs,omitempty"`
	// WKT of the field's Cells (POLYGON or MULTIPOLYGON).
	GeometryWkt []byte `protobuf:"bytes,3,opt,name=geometry_wkt,json=geometryWkt,proto3" json:"geometry_wkt,omitempty"`
	// Local-metric origin used for projection.
	RefPoint      *Point `protobuf:"bytes,4,opt,name=ref_point,json=refPoint,proto3" json:"ref_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_f2c_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Field) GetCrs() *CRS {
	if x != nil {
		return x.Crs
	}
	return nil
}

func (x *Field) GetGeometryWkt() []byte {
	if x != nil {
		return x.GeometryWkt
	}
	return nil
}

func (x *Field) GetRefPoint() *Point {
	if x != nil {
		return x.RefPoint
	}
	return nil
}

// A Field augmented with computed headlands and the inner cultivable area.
type FieldWithHeadlands struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// WKT of the headland rings (MULTILINESTRING or MULTIPOLYGON).
	HeadlandsWkt []byte `protobuf:"bytes,2,opt,name=headlands_wkt,json=headlandsWkt,proto3" json:"headlands_wkt,omitempty"`
	// WKT of the inner cells (field minus headlands).
	InnerFieldWkt  []byte  `protobuf:"bytes,3,opt,name=inner_field_wkt,json=innerFieldWkt,proto3" json:"inner_field_wkt,omitempty"`
	HeadlandWidthM float64 `protobuf:"fixed64,4,opt,name=headland_width_m,json=headlandWidthM,proto3" json:"headland_width_m,omitempty"`
	HeadlandCount  int32   `protobuf:"varint,5,opt,name=headland_count,json=headlandCount,proto3" json:"headland_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldWithHeadlands) Reset() {
	*x = FieldWithHeadlands{}
	mi := &file_f2c_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldWithHeadlands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldWithHeadlands) ProtoMessage() {}

func (x *FieldWithHeadlands) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldWithHeadlands.ProtoReflect.Descriptor instead.
func (*FieldWithHeadlands) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{3}
}

func (x *FieldWithHeadlands) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *FieldWithHeadlands) GetHeadlandsWkt() []byte {
	if x != nil {
		return x.HeadlandsWkt
	}
	return nil
}

func (x *FieldWithHeadlands) GetInnerFieldWkt() []byte {
	if x != nil {
		return x.InnerFieldWkt
	}
	return nil
}

func (x *FieldWithHeadlands) GetHeadlandWidthM() float64 {
	if x != nil {
		return x.HeadlandWidthM
	}
	return 0
}

func (x *FieldWithHeadlands) GetHeadlandCount() int32 {
	if x != nil {
		return x.HeadlandCount
	}
	return 0
}

// Mirror of f2c::types::Robot.
type Robot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WidthM            float64                `protobuf:"fixed64,2,opt,name=width_m,json=widthM,proto3" json:"width_m,omitempty"`
	CovWidthM         float64                `protobuf:"fixed64,3,opt,name=cov_width_m,json=covWidthM,proto3" json:"cov_width_m,omitempty"`
	MinTurningRadiusM float64                `protobuf:"fixed64,4,opt,name=min_turning_radius_m,json=minTurningRadiusM,proto3" json:"min_turning_radius_m,omitempty"`
	MaxCurv           float64                `protobuf:"fixed64,5,opt,name=max_curv,json=maxCurv,proto3" json:"max_curv,omitempty"`
	MaxDiffCurv       float64                `protobuf:"fixed64,6,opt,name=max_diff_curv,json=maxDiffCurv,proto3" json:"max_diff_curv,omitempty"`
	CruiseVelMps      float64                `protobuf:"fixed64,7,opt,name=cruise_vel_mps,json=cruiseVelMps,proto3" json:"cruise_vel_mps,omitempty"`
	// Optional override for turn velocity; 0 = inherit cruise_vel.
	TurnVelMps    float64 `protobuf:"fixed64,8,opt,name=turn_vel_mps,json=turnVelMps,proto3" json:"turn_vel_mps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Robot) Reset() {
	*x = Robot{}
	mi := &file_f2c_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot) ProtoMessage() {}

func (x *Robot) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robot.ProtoReflect.Descriptor instead.
func (*Robot) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{4}
}

func (x *Robot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Robot) GetWidthM() float64 {
	if x != nil {
		return x.WidthM
	}
	return 0
}

func (x *Robot) GetCovWidthM() float64 {
	if x != nil {
		return x.CovWidthM
	}
	return 0
}

func (x *Robot) GetMinTurningRadiusM() float64 {
	if x != nil {
		return x.MinTurningRadiusM
	}
	return 0
}

func (x *Robot) GetMaxCurv() float64 {
	if x != nil {
		return x.MaxCurv
	}
	return 0
}

func (x *Robot) GetMaxDiffCurv() float64 {
	if x != nil {
		return x.MaxDiffCurv
	}
	return 0
}

func (x *Robot) GetCruiseVelMps() float64 {
	if x != nil {
		return x.CruiseVelMps
	}
	return 0
}

func (x *Robot) GetTurnVelMps() float64 {
	if x != nil {
		return x.TurnVelMps
	}
	return 0
}

// Mirror of f2c::types::Swath.
type Swath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// WKT LINESTRING of the swath path in the parent field's CRS.
	PathWkt       []byte    `protobuf:"bytes,2,opt,name=path_wkt,json=pathWkt,proto3" json:"path_wkt,omitempty"`
	WidthM        float64   `protobuf:"fixed64,3,opt,name=width_m,json=widthM,proto3" json:"width_m,omitempty"`
	Type          SwathType `protobuf:"varint,4,opt,name=type,proto3,enum=f2c.v1.SwathType" json:"type,omitempty"`
	CreationDir   bool      `protobuf:"varint,5,opt,name=creation_dir,json=creationDir,proto3" json:"creation_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swath) Reset() {
	*x = Swath{}
	mi := &file_f2c_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swath) ProtoMessage() {}

func (x *Swath) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swath.ProtoReflect.Descriptor instead.
func (*Swath) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{5}
}

func (x *Swath) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Swath) GetPathWkt() []byte {
	if x != nil {
		return x.PathWkt
	}
	return nil
}

func (x *Swath) GetWidthM() float64 {
	if x != nil {
		return x.WidthM
	}
	return 0
}

func (x *Swath) GetType() SwathType {
	if x != nil {
		return x.Type
	}
	return SwathType_SWATH_TYPE_UNSPECIFIED
}

func (x *Swath) GetCreationDir() bool {
	if x != nil {
		return x.CreationDir
	}
	return false
}

// Mirror of f2c::types::Swaths — an ordered collection of Swath bound to
// the Field they were generated for. The field is carried forward so
// sort/route/path RPCs do not need to re-parse.
type Swaths struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field *FieldWithHeadlands    `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Items []*Swath               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	// Set by SortSwaths; indicates the items are in traversal order.
	Sorted        bool `protobuf:"varint,3,opt,name=sorted,proto3" json:"sorted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swaths) Reset() {
	*x = Swaths{}
	mi := &file_f2c_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swaths) ProtoMessage() {}

func (x *Swaths) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swaths.ProtoReflect.Descriptor instead.
func (*Swaths) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{6}
}

func (x *Swaths) GetField() *FieldWithHeadlands {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Swaths) GetItems() []*Swath {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Swaths) GetSorted() bool {
	if x != nil {
		return x.Sorted
	}
	return false
}

// A turn connection between two swaths, as a MultiPoint in field CRS.
type RouteConnection struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FromSwathId int32                  `protobuf:"varint,1,opt,name=from_swath_id,json=fromSwathId,proto3" json:"from_swath_id,omitempty"`
	ToSwathId   int32                  `protobuf:"varint,2,opt,name=to_swath_id,json=toSwathId,proto3" json:"to_swath_id,omitempty"`
	// WKT MULTIPOINT of the turn connection vertices.
	PointsWkt     []byte `protobuf:"bytes,3,opt,name=points_wkt,json=pointsWkt,proto3" json:"points_wkt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteConnection) Reset() {
	*x = RouteConnection{}
	mi := &file_f2c_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConnection) ProtoMessage() {}

func (x *RouteConnection) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConnection.ProtoReflect.Descriptor instead.
func (*RouteConnection) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{7}
}

func (x *RouteConnection) GetFromSwathId() int32 {
	if x != nil {
		return x.FromSwathId
	}
	return 0
}

func (x *RouteConnection) GetToSwathId() int32 {
	if x != nil {
		return x.ToSwathId
	}
	return 0
}

func (x *RouteConnection) GetPointsWkt() []byte {
	if x != nil {
		return x.PointsWkt
	}
	return nil
}

// Mirror of f2c::types::Route.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field (with headlands) the route was planned for.
	Field *FieldWithHeadlands `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Ordered swaths (must be sorted=true).
	Swaths *Swaths `protobuf:"bytes,2,opt,name=swaths,proto3" json:"swaths,omitempty"`
	// Turn connections. connections[i] joins swath items[i] and items[i+1].
	Connections   []*RouteConnection `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_f2c_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{8}
}

func (x *Route) GetField() *FieldWithHeadlands {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Route) GetSwaths() *Swaths {
	if x != nil {
		return x.Swaths
	}
	return nil
}

func (x *Route) GetConnections() []*RouteConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

// Mirror of f2c::types::PathState.
type PathState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	AngleRad      float64                `protobuf:"fixed64,2,opt,name=angle_rad,json=angleRad,proto3" json:"angle_rad,omitempty"`
	LengthM       float64                `protobuf:"fixed64,3,opt,name=length_m,json=lengthM,proto3" json:"length_m,omitempty"`
	Velocity      float64                `protobuf:"fixed64,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Direction     PathDirection          `protobuf:"varint,5,opt,name=direction,proto3,enum=f2c.v1.PathDirection" json:"direction,omitempty"`
	SectionType   PathSectionType        `protobuf:"varint,6,opt,name=section_type,json=sectionType,proto3,enum=f2c.v1.PathSectionType" json:"section_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathState) Reset() {
	*x = PathState{}
	mi := &file_f2c_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathState) ProtoMessage() {}

func (x *PathState) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathState.ProtoReflect.Descriptor instead.
func (*PathState) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{9}
}

func (x *PathState) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *PathState) GetAngleRad() float64 {
	if x != nil {
		return x.AngleRad
	}
	return 0
}

func (x *PathState) GetLengthM() float64 {
	if x != nil {
		return x.LengthM
	}
	return 0
}

func (x *PathState) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *PathState) GetDirection() PathDirection {
	if x != nil {
		return x.Direction
	}
	return PathDirection_PATH_DIRECTION_UNSPECIFIED
}

func (x *PathState) GetSectionType() PathSectionType {
	if x != nil {
		return x.SectionType
	}
	return PathSectionType_PATH_SECTION_TYPE_UNSPECIFIED
}

// Mirror of f2c::types::Path. Terminal output.
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *FieldWithHeadlands    `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	States        []*PathState           `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
	LengthM       float64                `protobuf:"fixed64,3,opt,name=length_m,json=lengthM,proto3" json:"length_m,omitempty"`
	TaskTimeS     float64                `protobuf:"fixed64,4,opt,name=task_time_s,json=taskTimeS,proto3" json:"task_time_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_f2c_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{10}
}

func (x *Path) GetField() *FieldWithHeadlands {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Path) GetStates() []*PathState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *Path) GetLengthM() float64 {
	if x != nil {
		return x.LengthM
	}
	return 0
}

func (x *Path) GetTaskTimeS() float64 {
	if x != nil {
		return x.TaskTimeS
	}
	return 0
}

type ParseGeoJSONRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw GeoJSON FeatureCollection text.
	Geojson string `protobuf:"bytes,1,opt,name=geojson,proto3" json:"geojson,omitempty"`
	// Optional target CRS; if unset, the server picks a local UTM zone.
	TargetCrs *CRS `protobuf:"bytes,2,opt,name=target_crs,json=targetCrs,proto3" json:"target_crs,omitempty"`
	// Optional client-supplied id; if empty, the server generates one.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseGeoJSONRequest) Reset() {
	*x = ParseGeoJSONRequest{}
	mi := &file_f2c_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGeoJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGeoJSONRequest) ProtoMessage() {}

func (x *ParseGeoJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGeoJSONRequest.ProtoReflect.Descriptor instead.
func (*ParseGeoJSONRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{11}
}

func (x *ParseGeoJSONRequest) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

func (x *ParseGeoJSONRequest) GetTargetCrs() *CRS {
	if x != nil {
		return x.TargetCrs
	}
	return nil
}

func (x *ParseGeoJSONRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ParseGeoJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseGeoJSONResponse) Reset() {
	*x = ParseGeoJSONResponse{}
	mi := &file_f2c_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGeoJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGeoJSONResponse) ProtoMessage() {}

func (x *ParseGeoJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGeoJSONResponse.ProtoReflect.Descriptor instead.
func (*ParseGeoJSONResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{12}
}

func (x *ParseGeoJSONResponse) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type TransformToUTMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformToUTMRequest) Reset() {
	*x = TransformToUTMRequest{}
	mi := &file_f2c_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformToUTMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformToUTMRequest) ProtoMessage() {}

func (x *TransformToUTMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformToUTMRequest.ProtoReflect.Descriptor instead.
func (*TransformToUTMRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{13}
}

func (x *TransformToUTMRequest) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type TransformToUTMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformToUTMResponse) Reset() {
	*x = TransformToUTMResponse{}
	mi := &file_f2c_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformToUTMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformToUTMResponse) ProtoMessage() {}

func (x *TransformToUTMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformToUTMResponse.ProtoReflect.Descriptor instead.
func (*TransformToUTMResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{14}
}

func (x *TransformToUTMResponse) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type CloneFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneFieldRequest) Reset() {
	*x = CloneFieldRequest{}
	mi := &file_f2c_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneFieldRequest) ProtoMessage() {}

func (x *CloneFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneFieldRequest.ProtoReflect.Descriptor instead.
func (*CloneFieldRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{15}
}

func (x *CloneFieldRequest) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type CloneFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneFieldResponse) Reset() {
	*x = CloneFieldResponse{}
	mi := &file_f2c_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneFieldResponse) ProtoMessage() {}

func (x *CloneFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneFieldResponse.ProtoReflect.Descriptor instead.
func (*CloneFieldResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{16}
}

func (x *CloneFieldResponse) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type CloneRobotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robot         *Robot                 `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRobotRequest) Reset() {
	*x = CloneRobotRequest{}
	mi := &file_f2c_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRobotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRobotRequest) ProtoMessage() {}

func (x *CloneRobotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRobotRequest.ProtoReflect.Descriptor instead.
func (*CloneRobotRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{17}
}

func (x *CloneRobotRequest) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type CloneRobotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robot         *Robot                 `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRobotResponse) Reset() {
	*x = CloneRobotResponse{}
	mi := &file_f2c_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRobotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRobotResponse) ProtoMessage() {}

func (x *CloneRobotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRobotResponse.ProtoReflect.Descriptor instead.
func (*CloneRobotResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{18}
}

func (x *CloneRobotResponse) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type GenerateHeadlandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Robot         *Robot                 `protobuf:"bytes,2,opt,name=robot,proto3" json:"robot,omitempty"`
	WidthM        float64                `protobuf:"fixed64,3,opt,name=width_m,json=widthM,proto3" json:"width_m,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateHeadlandRequest) Reset() {
	*x = GenerateHeadlandRequest{}
	mi := &file_f2c_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHeadlandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHeadlandRequest) ProtoMessage() {}

func (x *GenerateHeadlandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHeadlandRequest.ProtoReflect.Descriptor instead.
func (*GenerateHeadlandRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateHeadlandRequest) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *GenerateHeadlandRequest) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *GenerateHeadlandRequest) GetWidthM() float64 {
	if x != nil {
		return x.WidthM
	}
	return 0
}

func (x *GenerateHeadlandRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenerateHeadlandResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FieldWithHeadlands *FieldWithHeadlands    `protobuf:"bytes,1,opt,name=field_with_headlands,json=fieldWithHeadlands,proto3" json:"field_with_headlands,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateHeadlandResponse) Reset() {
	*x = GenerateHeadlandResponse{}
	mi := &file_f2c_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHeadlandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHeadlandResponse) ProtoMessage() {}

func (x *GenerateHeadlandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHeadlandResponse.ProtoReflect.Descriptor instead.
func (*GenerateHeadlandResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateHeadlandResponse) GetFieldWithHeadlands() *FieldWithHeadlands {
	if x != nil {
		return x.FieldWithHeadlands
	}
	return nil
}

type GenerateSwathsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FieldWithHeadlands *FieldWithHeadlands    `protobuf:"bytes,1,opt,name=field_with_headlands,json=fieldWithHeadlands,proto3" json:"field_with_headlands,omitempty"`
	Robot              *Robot                 `protobuf:"bytes,2,opt,name=robot,proto3" json:"robot,omitempty"`
	// angle_rad is optional. When absent the server runs brute-force
	// optimisation (minimises swath count) to pick the best heading.
	AngleRad      *float64 `protobuf:"fixed64,3,opt,name=angle_rad,json=angleRad,proto3,oneof" json:"angle_rad,omitempty"`
	WidthM        float64  `protobuf:"fixed64,4,opt,name=width_m,json=widthM,proto3" json:"width_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSwathsRequest) Reset() {
	*x = GenerateSwathsRequest{}
	mi := &file_f2c_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSwathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSwathsRequest) ProtoMessage() {}

func (x *GenerateSwathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSwathsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSwathsRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateSwathsRequest) GetFieldWithHeadlands() *FieldWithHeadlands {
	if x != nil {
		return x.FieldWithHeadlands
	}
	return nil
}

func (x *GenerateSwathsRequest) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *GenerateSwathsRequest) GetAngleRad() float64 {
	if x != nil && x.AngleRad != nil {
		return *x.AngleRad
	}
	return 0
}

func (x *GenerateSwathsRequest) GetWidthM() float64 {
	if x != nil {
		return x.WidthM
	}
	return 0
}

type GenerateSwathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swaths        *Swaths                `protobuf:"bytes,1,opt,name=swaths,proto3" json:"swaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSwathsResponse) Reset() {
	*x = GenerateSwathsResponse{}
	mi := &file_f2c_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSwathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSwathsResponse) ProtoMessage() {}

func (x *GenerateSwathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSwathsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSwathsResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateSwathsResponse) GetSwaths() *Swaths {
	if x != nil {
		return x.Swaths
	}
	return nil
}

type SortSwathsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Swaths    *Swaths                `protobuf:"bytes,1,opt,name=swaths,proto3" json:"swaths,omitempty"`
	Algorithm SortAlgorithm          `protobuf:"varint,2,opt,name=algorithm,proto3,enum=f2c.v1.SortAlgorithm" json:"algorithm,omitempty"`
	Variant   int32                  `protobuf:"varint,3,opt,name=variant,proto3" json:"variant,omitempty"`
	// When set, the server iterates all sort variants and returns the one
	// whose first swath start is closest to this point (projected UTM coords).
	// When absent, uses the variant field as before.
	StartPoint    *Point `protobuf:"bytes,4,opt,name=start_point,json=startPoint,proto3,oneof" json:"start_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortSwathsRequest) Reset() {
	*x = SortSwathsRequest{}
	mi := &file_f2c_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortSwathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortSwathsRequest) ProtoMessage() {}

func (x *SortSwathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortSwathsRequest.ProtoReflect.Descriptor instead.
func (*SortSwathsRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{23}
}

func (x *SortSwathsRequest) GetSwaths() *Swaths {
	if x != nil {
		return x.Swaths
	}
	return nil
}

func (x *SortSwathsRequest) GetAlgorithm() SortAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return SortAlgorithm_SORT_ALGORITHM_UNSPECIFIED
}

func (x *SortSwathsRequest) GetVariant() int32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

func (x *SortSwathsRequest) GetStartPoint() *Point {
	if x != nil {
		return x.StartPoint
	}
	return nil
}

type SortSwathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swaths        *Swaths                `protobuf:"bytes,1,opt,name=swaths,proto3" json:"swaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortSwathsResponse) Reset() {
	*x = SortSwathsResponse{}
	mi := &file_f2c_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortSwathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortSwathsResponse) ProtoMessage() {}

func (x *SortSwathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortSwathsResponse.ProtoReflect.Descriptor instead.
func (*SortSwathsResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{24}
}

func (x *SortSwathsResponse) GetSwaths() *Swaths {
	if x != nil {
		return x.Swaths
	}
	return nil
}

type GenerateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swaths        *Swaths                `protobuf:"bytes,1,opt,name=swaths,proto3" json:"swaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRouteRequest) Reset() {
	*x = GenerateRouteRequest{}
	mi := &file_f2c_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRouteRequest) ProtoMessage() {}

func (x *GenerateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRouteRequest.ProtoReflect.Descriptor instead.
func (*GenerateRouteRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{25}
}

func (x *GenerateRouteRequest) GetSwaths() *Swaths {
	if x != nil {
		return x.Swaths
	}
	return nil
}

type GenerateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRouteResponse) Reset() {
	*x = GenerateRouteResponse{}
	mi := &file_f2c_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRouteResponse) ProtoMessage() {}

func (x *GenerateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRouteResponse.ProtoReflect.Descriptor instead.
func (*GenerateRouteResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{26}
}

func (x *GenerateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type PlanPathRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Route            *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Robot            *Robot                 `protobuf:"bytes,2,opt,name=robot,proto3" json:"robot,omitempty"`
	TurningAlgorithm TurningAlgorithm       `protobuf:"varint,3,opt,name=turning_algorithm,json=turningAlgorithm,proto3,enum=f2c.v1.TurningAlgorithm" json:"turning_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanPathRequest) Reset() {
	*x = PlanPathRequest{}
	mi := &file_f2c_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPathRequest) ProtoMessage() {}

func (x *PlanPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPathRequest.ProtoReflect.Descriptor instead.
func (*PlanPathRequest) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{27}
}

func (x *PlanPathRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PlanPathRequest) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *PlanPathRequest) GetTurningAlgorithm() TurningAlgorithm {
	if x != nil {
		return x.TurningAlgorithm
	}
	return TurningAlgorithm_TURNING_ALGORITHM_UNSPECIFIED
}

type PlanPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *Path                  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPathResponse) Reset() {
	*x = PlanPathResponse{}
	mi := &file_f2c_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPathResponse) ProtoMessage() {}

func (x *PlanPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_f2c_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPathResponse.ProtoReflect.Descriptor instead.
func (*PlanPathResponse) Descriptor() ([]byte, []int) {
	return file_f2c_proto_rawDescGZIP(), []int{28}
}

func (x *PlanPathResponse) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_f2c_proto protoreflect.FileDescriptor

const file_f2c_proto_rawDesc = "" +
	"\n" +
	"\tf2c.proto\x12\x06f2c.v1\"F\n" +
	"\x03CRS\x12\x12\n" +
	"\x04epsg\x18\x01 \x01(\x05R\x04epsg\x12\x19\n" +
	"\butm_zone\x18\x02 \x01(\tR\autmZone\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x85\x01\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x03crs\x18\x02 \x01(\v2\v.f2c.v1.CRSR\x03crs\x12!\n" +
	"\fgeometry_wkt\x18\x03 \x01(\fR\vgeometryWkt\x12*\n" +
	"\tref_point\x18\x04 \x01(\v2\r.f2c.v1.PointR\brefPoint\"\xd7\x01\n" +
	"\x12FieldWithHeadlands\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\x12#\n" +
	"\rheadlands_wkt\x18\x02 \x01(\fR\fheadlandsWkt\x12&\n" +
	"\x0finner_field_wkt\x18\x03 \x01(\fR\rinnerFieldWkt\x12(\n" +
	"\x10headland_width_m\x18\x04 \x01(\x01R\x0eheadlandWidthM\x12%\n" +
	"\x0eheadland_count\x18\x05 \x01(\x05R\rheadlandCount\"\x8c\x02\n" +
	"\x05Robot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\awidth_m\x18\x02 \x01(\x01R\x06widthM\x12\x1e\n" +
	"\vcov_width_m\x18\x03 \x01(\x01R\tcovWidthM\x12/\n" +
	"\x14min_turning_radius_m\x18\x04 \x01(\x01R\x11minTurningRadiusM\x12\x19\n" +
	"\bmax_curv\x18\x05 \x01(\x01R\amaxCurv\x12\"\n" +
	"\rmax_diff_curv\x18\x06 \x01(\x01R\vmaxDiffCurv\x12$\n" +
	"\x0ecruise_vel_mps\x18\a \x01(\x01R\fcruiseVelMps\x12 \n" +
	"\fturn_vel_mps\x18\b \x01(\x01R\n" +
	"turnVelMps\"\x95\x01\n" +
	"\x05Swath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bpath_wkt\x18\x02 \x01(\fR\apathWkt\x12\x17\n" +
	"\awidth_m\x18\x03 \x01(\x01R\x06widthM\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.f2c.v1.SwathTypeR\x04type\x12!\n" +
	"\fcreation_dir\x18\x05 \x01(\bR\vcreationDir\"w\n" +
	"\x06Swaths\x120\n" +
	"\x05field\x18\x01 \x01(\v2\x1a.f2c.v1.FieldWithHeadlandsR\x05field\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.f2c.v1.SwathR\x05items\x12\x16\n" +
	"\x06sorted\x18\x03 \x01(\bR\x06sorted\"t\n" +
	"\x0fRouteConnection\x12\"\n" +
	"\rfrom_swath_id\x18\x01 \x01(\x05R\vfromSwathId\x12\x1e\n" +
	"\vto_swath_id\x18\x02 \x01(\x05R\ttoSwathId\x12\x1d\n" +
	"\n" +
	"points_wkt\x18\x03 \x01(\fR\tpointsWkt\"\x9c\x01\n" +
	"\x05Route\x120\n" +
	"\x05field\x18\x01 \x01(\v2\x1a.f2c.v1.FieldWithHeadlandsR\x05field\x12&\n" +
	"\x06swaths\x18\x02 \x01(\v2\x0e.f2c.v1.SwathsR\x06swaths\x129\n" +
	"\vconnections\x18\x03 \x03(\v2\x17.f2c.v1.RouteConnectionR\vconnections\"\xf5\x01\n" +
	"\tPathState\x12#\n" +
	"\x05point\x18\x01 \x01(\v2\r.f2c.v1.PointR\x05point\x12\x1b\n" +
	"\tangle_rad\x18\x02 \x01(\x01R\bangleRad\x12\x19\n" +
	"\blength_m\x18\x03 \x01(\x01R\alengthM\x12\x1a\n" +
	"\bvelocity\x18\x04 \x01(\x01R\bvelocity\x123\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x15.f2c.v1.PathDirectionR\tdirection\x12:\n" +
	"\fsection_type\x18\x06 \x01(\x0e2\x17.f2c.v1.PathSectionTypeR\vsectionType\"\x9e\x01\n" +
	"\x04Path\x120\n" +
	"\x05field\x18\x01 \x01(\v2\x1a.f2c.v1.FieldWithHeadlandsR\x05field\x12)\n" +
	"\x06states\x18\x02 \x03(\v2\x11.f2c.v1.PathStateR\x06states\x12\x19\n" +
	"\blength_m\x18\x03 \x01(\x01R\alengthM\x12\x1e\n" +
	"\vtask_time_s\x18\x04 \x01(\x01R\ttaskTimeS\"k\n" +
	"\x13ParseGeoJSONRequest\x12\x18\n" +
	"\ageojson\x18\x01 \x01(\tR\ageojson\x12*\n" +
	"\n" +
	"target_crs\x18\x02 \x01(\v2\v.f2c.v1.CRSR\ttargetCrs\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\";\n" +
	"\x14ParseGeoJSONResponse\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\"<\n" +
	"\x15TransformToUTMRequest\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\"=\n" +
	"\x16TransformToUTMResponse\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\"8\n" +
	"\x11CloneFieldRequest\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\"9\n" +
	"\x12CloneFieldResponse\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\"8\n" +
	"\x11CloneRobotRequest\x12#\n" +
	"\x05robot\x18\x01 \x01(\v2\r.f2c.v1.RobotR\x05robot\"9\n" +
	"\x12CloneRobotResponse\x12#\n" +
	"\x05robot\x18\x01 \x01(\v2\r.f2c.v1.RobotR\x05robot\"\x92\x01\n" +
	"\x17GenerateHeadlandRequest\x12#\n" +
	"\x05field\x18\x01 \x01(\v2\r.f2c.v1.FieldR\x05field\x12#\n" +
	"\x05robot\x18\x02 \x01(\v2\r.f2c.v1.RobotR\x05robot\x12\x17\n" +
	"\awidth_m\x18\x03 \x01(\x01R\x06widthM\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"h\n" +
	"\x18GenerateHeadlandResponse\x12L\n" +
	"\x14field_with_headlands\x18\x01 \x01(\v2\x1a.f2c.v1.FieldWithHeadlandsR\x12fieldWithHeadlands\"\xd3\x01\n" +
	"\x15GenerateSwathsRequest\x12L\n" +
	"\x14field_with_headlands\x18\x01 \x01(\v2\x1a.f2c.v1.FieldWithHeadlandsR\x12fieldWithHeadlands\x12#\n" +
	"\x05robot\x18\x02 \x01(\v2\r.f2c.v1.RobotR\x05robot\x12 \n" +
	"\tangle_rad\x18\x03 \x01(\x01H\x00R\bangleRad\x88\x01\x01\x12\x17\n" +
	"\awidth_m\x18\x04 \x01(\x01R\x06widthMB\f\n" +
	"\n" +
	"_angle_rad\"@\n" +
	"\x16GenerateSwathsResponse\x12&\n" +
	"\x06swaths\x18\x01 \x01(\v2\x0e.f2c.v1.SwathsR\x06swaths\"\xcf\x01\n" +
	"\x11SortSwathsRequest\x12&\n" +
	"\x06swaths\x18\x01 \x01(\v2\x0e.f2c.v1.SwathsR\x06swaths\x123\n" +
	"\talgorithm\x18\x02 \x01(\x0e2\x15.f2c.v1.SortAlgorithmR\talgorithm\x12\x18\n" +
	"\avariant\x18\x03 \x01(\x05R\avariant\x123\n" +
	"\vstart_point\x18\x04 \x01(\v2\r.f2c.v1.PointH\x00R\n" +
	"startPoint\x88\x01\x01B\x0e\n" +
	"\f_start_point\"<\n" +
	"\x12SortSwathsResponse\x12&\n" +
	"\x06swaths\x18\x01 \x01(\v2\x0e.f2c.v1.SwathsR\x06swaths\">\n" +
	"\x14GenerateRouteRequest\x12&\n" +
	"\x06swaths\x18\x01 \x01(\v2\x0e.f2c.v1.SwathsR\x06swaths\"<\n" +
	"\x15GenerateRouteResponse\x12#\n" +
	"\x05route\x18\x01 \x01(\v2\r.f2c.v1.RouteR\x05route\"\xa2\x01\n" +
	"\x0fPlanPathRequest\x12#\n" +
	"\x05route\x18\x01 \x01(\v2\r.f2c.v1.RouteR\x05route\x12#\n" +
	"\x05robot\x18\x02 \x01(\v2\r.f2c.v1.RobotR\x05robot\x12E\n" +
	"\x11turning_algorithm\x18\x03 \x01(\x0e2\x18.f2c.v1.TurningAlgorithmR\x10turningAlgorithm\"4\n" +
	"\x10PlanPathResponse\x12 \n" +
	"\x04path\x18\x01 \x01(\v2\f.f2c.v1.PathR\x04path*Y\n" +
	"\tSwathType\x12\x1a\n" +
	"\x16SWATH_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SWATH_TYPE_MAINLAND\x10\x01\x12\x17\n" +
	"\x13SWATH_TYPE_HEADLAND\x10\x02*h\n" +
	"\rPathDirection\x12\x1e\n" +
	"\x1aPATH_DIRECTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PATH_DIRECTION_FORWARD\x10\x01\x12\x1b\n" +
	"\x17PATH_DIRECTION_BACKWARD\x10\x02*m\n" +
	"\x0fPathSectionType\x12!\n" +
	"\x1dPATH_SECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PATH_SECTION_TYPE_SWATH\x10\x01\x12\x1a\n" +
	"\x16PATH_SECTION_TYPE_TURN\x10\x02*\x86\x01\n" +
	"\rSortAlgorithm\x12\x1e\n" +
	"\x1aSORT_ALGORITHM_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSORT_ALGORITHM_BOUSTROPHEDON\x10\x01\x12\x18\n" +
	"\x14SORT_ALGORITHM_SNAKE\x10\x02\x12\x19\n" +
	"\x15SORT_ALGORITHM_SPIRAL\x10\x03*\xbd\x01\n" +
	"\x10TurningAlgorithm\x12!\n" +
	"\x1dTURNING_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TURNING_ALGORITHM_DUBINS\x10\x01\x12\x1f\n" +
	"\x1bTURNING_ALGORITHM_DUBINS_CC\x10\x02\x12!\n" +
	"\x1dTURNING_ALGORITHM_REEDS_SHEPP\x10\x03\x12$\n" +
	" TURNING_ALGORITHM_REEDS_SHEPP_HC\x10\x042\xa5\x05\n" +
	"\x03F2C\x12I\n" +
	"\fParseGeoJSON\x12\x1b.f2c.v1.ParseGeoJSONRequest\x1a\x1c.f2c.v1.ParseGeoJSONResponse\x12O\n" +
	"\x0eTransformToUTM\x12\x1d.f2c.v1.TransformToUTMRequest\x1a\x1e.f2c.v1.TransformToUTMResponse\x12C\n" +
	"\n" +
	"CloneField\x12\x19.f2c.v1.CloneFieldRequest\x1a\x1a.f2c.v1.CloneFieldResponse\x12C\n" +
	"\n" +
	"CloneRobot\x12\x19.f2c.v1.CloneRobotRequest\x1a\x1a.f2c.v1.CloneRobotResponse\x12U\n" +
	"\x10GenerateHeadland\x12\x1f.f2c.v1.GenerateHeadlandRequest\x1a .f2c.v1.GenerateHeadlandResponse\x12O\n" +
	"\x0eGenerateSwaths\x12\x1d.f2c.v1.GenerateSwathsRequest\x1a\x1e.f2c.v1.GenerateSwathsResponse\x12C\n" +
	"\n" +
	"SortSwaths\x12\x19.f2c.v1.SortSwathsRequest\x1a\x1a.f2c.v1.SortSwathsResponse\x12L\n" +
	"\rGenerateRoute\x12\x1c.f2c.v1.GenerateRouteRequest\x1a\x1d.f2c.v1.GenerateRouteResponse\x12=\n" +
	"\bPlanPath\x12\x17.f2c.v1.PlanPathRequest\x1a\x18.f2c.v1.PlanPathResponseB<Z7github.com/Fields2Cover/fields2cover/proto/f2c/v1;f2cv1\xf8\x01\x01b\x06proto3"

var (
	file_f2c_proto_rawDescOnce sync.Once
	file_f2c_proto_rawDescData []byte
)

func file_f2c_proto_rawDescGZIP() []byte {
	file_f2c_proto_rawDescOnce.Do(func() {
		file_f2c_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_f2c_proto_rawDesc), len(file_f2c_proto_rawDesc)))
	})
	return file_f2c_proto_rawDescData
}

var file_f2c_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_f2c_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_f2c_proto_goTypes = []any{
	(SwathType)(0),                   // 0: f2c.v1.SwathType
	(PathDirection)(0),               // 1: f2c.v1.PathDirection
	(PathSectionType)(0),             // 2: f2c.v1.PathSectionType
	(SortAlgorithm)(0),               // 3: f2c.v1.SortAlgorithm
	(TurningAlgorithm)(0),            // 4: f2c.v1.TurningAlgorithm
	(*CRS)(nil),                      // 5: f2c.v1.CRS
	(*Point)(nil),                    // 6: f2c.v1.Point
	(*Field)(nil),                    // 7: f2c.v1.Field
	(*FieldWithHeadlands)(nil),       // 8: f2c.v1.FieldWithHeadlands
	(*Robot)(nil),                    // 9: f2c.v1.Robot
	(*Swath)(nil),                    // 10: f2c.v1.Swath
	(*Swaths)(nil),                   // 11: f2c.v1.Swaths
	(*RouteConnection)(nil),          // 12: f2c.v1.RouteConnection
	(*Route)(nil),                    // 13: f2c.v1.Route
	(*PathState)(nil),                // 14: f2c.v1.PathState
	(*Path)(nil),                     // 15: f2c.v1.Path
	(*ParseGeoJSONRequest)(nil),      // 16: f2c.v1.ParseGeoJSONRequest
	(*ParseGeoJSONResponse)(nil),     // 17: f2c.v1.ParseGeoJSONResponse
	(*TransformToUTMRequest)(nil),    // 18: f2c.v1.TransformToUTMRequest
	(*TransformToUTMResponse)(nil),   // 19: f2c.v1.TransformToUTMResponse
	(*CloneFieldRequest)(nil),        // 20: f2c.v1.CloneFieldRequest
	(*CloneFieldResponse)(nil),       // 21: f2c.v1.CloneFieldResponse
	(*CloneRobotRequest)(nil),        // 22: f2c.v1.CloneRobotRequest
	(*CloneRobotResponse)(nil),       // 23: f2c.v1.CloneRobotResponse
	(*GenerateHeadlandRequest)(nil),  // 24: f2c.v1.GenerateHeadlandRequest
	(*GenerateHeadlandResponse)(nil), // 25: f2c.v1.GenerateHeadlandResponse
	(*GenerateSwathsRequest)(nil),    // 26: f2c.v1.GenerateSwathsRequest
	(*GenerateSwathsResponse)(nil),   // 27: f2c.v1.GenerateSwathsResponse
	(*SortSwathsRequest)(nil),        // 28: f2c.v1.SortSwathsRequest
	(*SortSwathsResponse)(nil),       // 29: f2c.v1.SortSwathsResponse
	(*GenerateRouteRequest)(nil),     // 30: f2c.v1.GenerateRouteRequest
	(*GenerateRouteResponse)(nil),    // 31: f2c.v1.GenerateRouteResponse
	(*PlanPathRequest)(nil),          // 32: f2c.v1.PlanPathRequest
	(*PlanPathResponse)(nil),         // 33: f2c.v1.PlanPathResponse
}
var file_f2c_proto_depIdxs = []int32{
	5,  // 0: f2c.v1.Field.crs:type_name -> f2c.v1.CRS
	6,  // 1: f2c.v1.Field.ref_point:type_name -> f2c.v1.Point
	7,  // 2: f2c.v1.FieldWithHeadlands.field:type_name -> f2c.v1.Field
	0,  // 3: f2c.v1.Swath.type:type_name -> f2c.v1.SwathType
	8,  // 4: f2c.v1.Swaths.field:type_name -> f2c.v1.FieldWithHeadlands
	10, // 5: f2c.v1.Swaths.items:type_name -> f2c.v1.Swath
	8,  // 6: f2c.v1.Route.field:type_name -> f2c.v1.FieldWithHeadlands
	11, // 7: f2c.v1.Route.swaths:type_name -> f2c.v1.Swaths
	12, // 8: f2c.v1.Route.connections:type_name -> f2c.v1.RouteConnection
	6,  // 9: f2c.v1.PathState.point:type_name -> f2c.v1.Point
	1,  // 10: f2c.v1.PathState.direction:type_name -> f2c.v1.PathDirection
	2,  // 11: f2c.v1.PathState.section_type:type_name -> f2c.v1.PathSectionType
	8,  // 12: f2c.v1.Path.field:type_name -> f2c.v1.FieldWithHeadlands
	14, // 13: f2c.v1.Path.states:type_name -> f2c.v1.PathState
	5,  // 14: f2c.v1.ParseGeoJSONRequest.target_crs:type_name -> f2c.v1.CRS
	7,  // 15: f2c.v1.ParseGeoJSONResponse.field:type_name -> f2c.v1.Field
	7,  // 16: f2c.v1.TransformToUTMRequest.field:type_name -> f2c.v1.Field
	7,  // 17: f2c.v1.TransformToUTMResponse.field:type_name -> f2c.v1.Field
	7,  // 18: f2c.v1.CloneFieldRequest.field:type_name -> f2c.v1.Field
	7,  // 19: f2c.v1.CloneFieldResponse.field:type_name -> f2c.v1.Field
	9,  // 20: f2c.v1.CloneRobotRequest.robot:type_name -> f2c.v1.Robot
	9,  // 21: f2c.v1.CloneRobotResponse.robot:type_name -> f2c.v1.Robot
	7,  // 22: f2c.v1.GenerateHeadlandRequest.field:type_name -> f2c.v1.Field
	9,  // 23: f2c.v1.GenerateHeadlandRequest.robot:type_name -> f2c.v1.Robot
	8,  // 24: f2c.v1.GenerateHeadlandResponse.field_with_headlands:type_name -> f2c.v1.FieldWithHeadlands
	8,  // 25: f2c.v1.GenerateSwathsRequest.field_with_headlands:type_name -> f2c.v1.FieldWithHeadlands
	9,  // 26: f2c.v1.GenerateSwathsRequest.robot:type_name -> f2c.v1.Robot
	11, // 27: f2c.v1.GenerateSwathsResponse.swaths:type_name -> f2c.v1.Swaths
	11, // 28: f2c.v1.SortSwathsRequest.swaths:type_name -> f2c.v1.Swaths
	3,  // 29: f2c.v1.SortSwathsRequest.algorithm:type_name -> f2c.v1.SortAlgorithm
	6,  // 30: f2c.v1.SortSwathsRequest.start_point:type_name -> f2c.v1.Point
	11, // 31: f2c.v1.SortSwathsResponse.swaths:type_name -> f2c.v1.Swaths
	11, // 32: f2c.v1.GenerateRouteRequest.swaths:type_name -> f2c.v1.Swaths
	13, // 33: f2c.v1.GenerateRouteResponse.route:type_name -> f2c.v1.Route
	13, // 34: f2c.v1.PlanPathRequest.route:type_name -> f2c.v1.Route
	9,  // 35: f2c.v1.PlanPathRequest.robot:type_name -> f2c.v1.Robot
	4,  // 36: f2c.v1.PlanPathRequest.turning_algorithm:type_name -> f2c.v1.TurningAlgorithm
	15, // 37: f2c.v1.PlanPathResponse.path:type_name -> f2c.v1.Path
	16, // 38: f2c.v1.F2C.ParseGeoJSON:input_type -> f2c.v1.ParseGeoJSONRequest
	18, // 39: f2c.v1.F2C.TransformToUTM:input_type -> f2c.v1.TransformToUTMRequest
	20, // 40: f2c.v1.F2C.CloneField:input_type -> f2c.v1.CloneFieldRequest
	22, // 41: f2c.v1.F2C.CloneRobot:input_type -> f2c.v1.CloneRobotRequest
	24, // 42: f2c.v1.F2C.GenerateHeadland:input_type -> f2c.v1.GenerateHeadlandRequest
	26, // 43: f2c.v1.F2C.GenerateSwaths:input_type -> f2c.v1.GenerateSwathsRequest
	28, // 44: f2c.v1.F2C.SortSwaths:input_type -> f2c.v1.SortSwathsRequest
	30, // 45: f2c.v1.F2C.GenerateRoute:input_type -> f2c.v1.GenerateRouteRequest
	32, // 46: f2c.v1.F2C.PlanPath:input_type -> f2c.v1.PlanPathRequest
	17, // 47: f2c.v1.F2C.ParseGeoJSON:output_type -> f2c.v1.ParseGeoJSONResponse
	19, // 48: f2c.v1.F2C.TransformToUTM:output_type -> f2c.v1.TransformToUTMResponse
	21, // 49: f2c.v1.F2C.CloneField:output_type -> f2c.v1.CloneFieldResponse
	23, // 50: f2c.v1.F2C.CloneRobot:output_type -> f2c.v1.CloneRobotResponse
	25, // 51: f2c.v1.F2C.GenerateHeadland:output_type -> f2c.v1.GenerateHeadlandResponse
	27, // 52: f2c.v1.F2C.GenerateSwaths:output_type -> f2c.v1.GenerateSwathsResponse
	29, // 53: f2c.v1.F2C.SortSwaths:output_type -> f2c.v1.SortSwathsResponse
	31, // 54: f2c.v1.F2C.GenerateRoute:output_type -> f2c.v1.GenerateRouteResponse
	33, // 55: f2c.v1.F2C.PlanPath:output_type -> f2c.v1.PlanPathResponse
	47, // [47:56] is the sub-list for method output_type
	38, // [38:47] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_f2c_proto_init() }
func file_f2c_proto_init() {
	if File_f2c_proto != nil {
		return
	}
	file_f2c_proto_msgTypes[21].OneofWrappers = []any{}
	file_f2c_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_f2c_proto_rawDesc), len(file_f2c_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_f2c_proto_goTypes,
		DependencyIndexes: file_f2c_proto_depIdxs,
		EnumInfos:         file_f2c_proto_enumTypes,
		MessageInfos:      file_f2c_proto_msgTypes,
	}.Build()
	File_f2c_proto = out.File
	file_f2c_proto_goTypes = nil
	file_f2c_proto_depIdxs = nil
}
