// Copyright (C) 2026 Wageningen University — BSD-3-Clause
//
// Internal gRPC contract between the Go API server and the f2c C++ shim.
// This file is the single source of truth for what f2c operations the Go API
// can invoke. The C++ server (phase 10) and Go client (phase 11) are both
// generated from this file.
//
// IMPORTANT: This contract is DISJOINT from api-go/openapi.yaml on purpose.
// The Go handler layer explicitly converts between OpenAPI (inline GeoJSON)
// and these proto messages (WKT bytes). See docs/contracts.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: f2c.proto

package f2cclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	F2C_ParseGeoJSON_FullMethodName     = "/f2c.v1.F2C/ParseGeoJSON"
	F2C_TransformToUTM_FullMethodName   = "/f2c.v1.F2C/TransformToUTM"
	F2C_CloneField_FullMethodName       = "/f2c.v1.F2C/CloneField"
	F2C_CloneRobot_FullMethodName       = "/f2c.v1.F2C/CloneRobot"
	F2C_GenerateHeadland_FullMethodName = "/f2c.v1.F2C/GenerateHeadland"
	F2C_GenerateSwaths_FullMethodName   = "/f2c.v1.F2C/GenerateSwaths"
	F2C_SortSwaths_FullMethodName       = "/f2c.v1.F2C/SortSwaths"
	F2C_GenerateRoute_FullMethodName    = "/f2c.v1.F2C/GenerateRoute"
	F2C_PlanPath_FullMethodName         = "/f2c.v1.F2C/PlanPath"
)

// F2CClient is the client API for F2C service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// F2C exposes the fields2cover C++ operations that the Go API needs.
// Exactly 9 RPCs — one per f2c operation on the journey surface.
type F2CClient interface {
	// Parse an inline GeoJSON FeatureCollection into a typed Field.
	ParseGeoJSON(ctx context.Context, in *ParseGeoJSONRequest, opts ...grpc.CallOption) (*ParseGeoJSONResponse, error)
	// Project a Field from one CRS to a local UTM zone.
	TransformToUTM(ctx context.Context, in *TransformToUTMRequest, opts ...grpc.CallOption) (*TransformToUTMResponse, error)
	// Deep-copy a Field (used by the handler layer to isolate requests).
	CloneField(ctx context.Context, in *CloneFieldRequest, opts ...grpc.CallOption) (*CloneFieldResponse, error)
	// Deep-copy a Robot.
	CloneRobot(ctx context.Context, in *CloneRobotRequest, opts ...grpc.CallOption) (*CloneRobotResponse, error)
	// Generate headland rings + inner cultivable area for a Field.
	GenerateHeadland(ctx context.Context, in *GenerateHeadlandRequest, opts ...grpc.CallOption) (*GenerateHeadlandResponse, error)
	// Generate coverage swaths inside a FieldWithHeadlands.
	GenerateSwaths(ctx context.Context, in *GenerateSwathsRequest, opts ...grpc.CallOption) (*GenerateSwathsResponse, error)
	// Order swaths into a traversal sequence (Boustrophedon, Snake, Spiral).
	SortSwaths(ctx context.Context, in *SortSwathsRequest, opts ...grpc.CallOption) (*SortSwathsResponse, error)
	// Build a route with turn connections between sorted swath groups.
	GenerateRoute(ctx context.Context, in *GenerateRouteRequest, opts ...grpc.CallOption) (*GenerateRouteResponse, error)
	// Plan a smooth drivable Path from a Route (terminal step).
	PlanPath(ctx context.Context, in *PlanPathRequest, opts ...grpc.CallOption) (*PlanPathResponse, error)
}

type f2CClient struct {
	cc grpc.ClientConnInterface
}

func NewF2CClient(cc grpc.ClientConnInterface) F2CClient {
	return &f2CClient{cc}
}

func (c *f2CClient) ParseGeoJSON(ctx context.Context, in *ParseGeoJSONRequest, opts ...grpc.CallOption) (*ParseGeoJSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseGeoJSONResponse)
	err := c.cc.Invoke(ctx, F2C_ParseGeoJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) TransformToUTM(ctx context.Context, in *TransformToUTMRequest, opts ...grpc.CallOption) (*TransformToUTMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformToUTMResponse)
	err := c.cc.Invoke(ctx, F2C_TransformToUTM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) CloneField(ctx context.Context, in *CloneFieldRequest, opts ...grpc.CallOption) (*CloneFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneFieldResponse)
	err := c.cc.Invoke(ctx, F2C_CloneField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) CloneRobot(ctx context.Context, in *CloneRobotRequest, opts ...grpc.CallOption) (*CloneRobotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneRobotResponse)
	err := c.cc.Invoke(ctx, F2C_CloneRobot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) GenerateHeadland(ctx context.Context, in *GenerateHeadlandRequest, opts ...grpc.CallOption) (*GenerateHeadlandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateHeadlandResponse)
	err := c.cc.Invoke(ctx, F2C_GenerateHeadland_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) GenerateSwaths(ctx context.Context, in *GenerateSwathsRequest, opts ...grpc.CallOption) (*GenerateSwathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSwathsResponse)
	err := c.cc.Invoke(ctx, F2C_GenerateSwaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) SortSwaths(ctx context.Context, in *SortSwathsRequest, opts ...grpc.CallOption) (*SortSwathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortSwathsResponse)
	err := c.cc.Invoke(ctx, F2C_SortSwaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) GenerateRoute(ctx context.Context, in *GenerateRouteRequest, opts ...grpc.CallOption) (*GenerateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRouteResponse)
	err := c.cc.Invoke(ctx, F2C_GenerateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *f2CClient) PlanPath(ctx context.Context, in *PlanPathRequest, opts ...grpc.CallOption) (*PlanPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanPathResponse)
	err := c.cc.Invoke(ctx, F2C_PlanPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// F2CServer is the server API for F2C service.
// All implementations must embed UnimplementedF2CServer
// for forward compatibility.
//
// F2C exposes the fields2cover C++ operations that the Go API needs.
// Exactly 9 RPCs — one per f2c operation on the journey surface.
type F2CServer interface {
	// Parse an inline GeoJSON FeatureCollection into a typed Field.
	ParseGeoJSON(context.Context, *ParseGeoJSONRequest) (*ParseGeoJSONResponse, error)
	// Project a Field from one CRS to a local UTM zone.
	TransformToUTM(context.Context, *TransformToUTMRequest) (*TransformToUTMResponse, error)
	// Deep-copy a Field (used by the handler layer to isolate requests).
	CloneField(context.Context, *CloneFieldRequest) (*CloneFieldResponse, error)
	// Deep-copy a Robot.
	CloneRobot(context.Context, *CloneRobotRequest) (*CloneRobotResponse, error)
	// Generate headland rings + inner cultivable area for a Field.
	GenerateHeadland(context.Context, *GenerateHeadlandRequest) (*GenerateHeadlandResponse, error)
	// Generate coverage swaths inside a FieldWithHeadlands.
	GenerateSwaths(context.Context, *GenerateSwathsRequest) (*GenerateSwathsResponse, error)
	// Order swaths into a traversal sequence (Boustrophedon, Snake, Spiral).
	SortSwaths(context.Context, *SortSwathsRequest) (*SortSwathsResponse, error)
	// Build a route with turn connections between sorted swath groups.
	GenerateRoute(context.Context, *GenerateRouteRequest) (*GenerateRouteResponse, error)
	// Plan a smooth drivable Path from a Route (terminal step).
	PlanPath(context.Context, *PlanPathRequest) (*PlanPathResponse, error)
	mustEmbedUnimplementedF2CServer()
}

// UnimplementedF2CServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedF2CServer struct{}

func (UnimplementedF2CServer) ParseGeoJSON(context.Context, *ParseGeoJSONRequest) (*ParseGeoJSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseGeoJSON not implemented")
}
func (UnimplementedF2CServer) TransformToUTM(context.Context, *TransformToUTMRequest) (*TransformToUTMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformToUTM not implemented")
}
func (UnimplementedF2CServer) CloneField(context.Context, *CloneFieldRequest) (*CloneFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneField not implemented")
}
func (UnimplementedF2CServer) CloneRobot(context.Context, *CloneRobotRequest) (*CloneRobotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneRobot not implemented")
}
func (UnimplementedF2CServer) GenerateHeadland(context.Context, *GenerateHeadlandRequest) (*GenerateHeadlandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateHeadland not implemented")
}
func (UnimplementedF2CServer) GenerateSwaths(context.Context, *GenerateSwathsRequest) (*GenerateSwathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSwaths not implemented")
}
func (UnimplementedF2CServer) SortSwaths(context.Context, *SortSwathsRequest) (*SortSwathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SortSwaths not implemented")
}
func (UnimplementedF2CServer) GenerateRoute(context.Context, *GenerateRouteRequest) (*GenerateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRoute not implemented")
}
func (UnimplementedF2CServer) PlanPath(context.Context, *PlanPathRequest) (*PlanPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanPath not implemented")
}
func (UnimplementedF2CServer) mustEmbedUnimplementedF2CServer() {}
func (UnimplementedF2CServer) testEmbeddedByValue()             {}

// UnsafeF2CServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to F2CServer will
// result in compilation errors.
type UnsafeF2CServer interface {
	mustEmbedUnimplementedF2CServer()
}

func RegisterF2CServer(s grpc.ServiceRegistrar, srv F2CServer) {
	// If the following call panics, it indicates UnimplementedF2CServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&F2C_ServiceDesc, srv)
}

func _F2C_ParseGeoJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseGeoJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).ParseGeoJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_ParseGeoJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).ParseGeoJSON(ctx, req.(*ParseGeoJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_TransformToUTM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformToUTMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).TransformToUTM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_TransformToUTM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).TransformToUTM(ctx, req.(*TransformToUTMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_CloneField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).CloneField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_CloneField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).CloneField(ctx, req.(*CloneFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_CloneRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRobotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).CloneRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_CloneRobot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).CloneRobot(ctx, req.(*CloneRobotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_GenerateHeadland_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateHeadlandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).GenerateHeadland(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_GenerateHeadland_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).GenerateHeadland(ctx, req.(*GenerateHeadlandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_GenerateSwaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSwathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).GenerateSwaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_GenerateSwaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).GenerateSwaths(ctx, req.(*GenerateSwathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_SortSwaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortSwathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).SortSwaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_SortSwaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).SortSwaths(ctx, req.(*SortSwathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_GenerateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).GenerateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_GenerateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).GenerateRoute(ctx, req.(*GenerateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _F2C_PlanPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2CServer).PlanPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: F2C_PlanPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2CServer).PlanPath(ctx, req.(*PlanPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// F2C_ServiceDesc is the grpc.ServiceDesc for F2C service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var F2C_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "f2c.v1.F2C",
	HandlerType: (*F2CServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseGeoJSON",
			Handler:    _F2C_ParseGeoJSON_Handler,
		},
		{
			MethodName: "TransformToUTM",
			Handler:    _F2C_TransformToUTM_Handler,
		},
		{
			MethodName: "CloneField",
			Handler:    _F2C_CloneField_Handler,
		},
		{
			MethodName: "CloneRobot",
			Handler:    _F2C_CloneRobot_Handler,
		},
		{
			MethodName: "GenerateHeadland",
			Handler:    _F2C_GenerateHeadland_Handler,
		},
		{
			MethodName: "GenerateSwaths",
			Handler:    _F2C_GenerateSwaths_Handler,
		},
		{
			MethodName: "SortSwaths",
			Handler:    _F2C_SortSwaths_Handler,
		},
		{
			MethodName: "GenerateRoute",
			Handler:    _F2C_GenerateRoute_Handler,
		},
		{
			MethodName: "PlanPath",
			Handler:    _F2C_PlanPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "f2c.proto",
}
